
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `DateSlot` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model DateSlot
 * 
 */
export type DateSlotModel = runtime.Types.Result.DefaultSelection<Prisma.$DateSlotPayload>

export type AggregateDateSlot = {
  _count: DateSlotCountAggregateOutputType | null
  _avg: DateSlotAvgAggregateOutputType | null
  _sum: DateSlotSumAggregateOutputType | null
  _min: DateSlotMinAggregateOutputType | null
  _max: DateSlotMaxAggregateOutputType | null
}

export type DateSlotAvgAggregateOutputType = {
  id: number | null
  timeSlotId: number | null
  serviceId: number | null
  maxCapacity: number | null
}

export type DateSlotSumAggregateOutputType = {
  id: bigint | null
  timeSlotId: bigint | null
  serviceId: bigint | null
  maxCapacity: number | null
}

export type DateSlotMinAggregateOutputType = {
  id: bigint | null
  date: Date | null
  timeSlotId: bigint | null
  serviceId: bigint | null
  maxCapacity: number | null
  createdAt: Date | null
}

export type DateSlotMaxAggregateOutputType = {
  id: bigint | null
  date: Date | null
  timeSlotId: bigint | null
  serviceId: bigint | null
  maxCapacity: number | null
  createdAt: Date | null
}

export type DateSlotCountAggregateOutputType = {
  id: number
  date: number
  timeSlotId: number
  serviceId: number
  maxCapacity: number
  createdAt: number
  _all: number
}


export type DateSlotAvgAggregateInputType = {
  id?: true
  timeSlotId?: true
  serviceId?: true
  maxCapacity?: true
}

export type DateSlotSumAggregateInputType = {
  id?: true
  timeSlotId?: true
  serviceId?: true
  maxCapacity?: true
}

export type DateSlotMinAggregateInputType = {
  id?: true
  date?: true
  timeSlotId?: true
  serviceId?: true
  maxCapacity?: true
  createdAt?: true
}

export type DateSlotMaxAggregateInputType = {
  id?: true
  date?: true
  timeSlotId?: true
  serviceId?: true
  maxCapacity?: true
  createdAt?: true
}

export type DateSlotCountAggregateInputType = {
  id?: true
  date?: true
  timeSlotId?: true
  serviceId?: true
  maxCapacity?: true
  createdAt?: true
  _all?: true
}

export type DateSlotAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which DateSlot to aggregate.
   */
  where?: Prisma.DateSlotWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of DateSlots to fetch.
   */
  orderBy?: Prisma.DateSlotOrderByWithRelationInput | Prisma.DateSlotOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.DateSlotWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` DateSlots from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` DateSlots.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned DateSlots
  **/
  _count?: true | DateSlotCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: DateSlotAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: DateSlotSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: DateSlotMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: DateSlotMaxAggregateInputType
}

export type GetDateSlotAggregateType<T extends DateSlotAggregateArgs> = {
      [P in keyof T & keyof AggregateDateSlot]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateDateSlot[P]>
    : Prisma.GetScalarType<T[P], AggregateDateSlot[P]>
}




export type DateSlotGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.DateSlotWhereInput
  orderBy?: Prisma.DateSlotOrderByWithAggregationInput | Prisma.DateSlotOrderByWithAggregationInput[]
  by: Prisma.DateSlotScalarFieldEnum[] | Prisma.DateSlotScalarFieldEnum
  having?: Prisma.DateSlotScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: DateSlotCountAggregateInputType | true
  _avg?: DateSlotAvgAggregateInputType
  _sum?: DateSlotSumAggregateInputType
  _min?: DateSlotMinAggregateInputType
  _max?: DateSlotMaxAggregateInputType
}

export type DateSlotGroupByOutputType = {
  id: bigint
  date: Date
  timeSlotId: bigint
  serviceId: bigint
  maxCapacity: number
  createdAt: Date
  _count: DateSlotCountAggregateOutputType | null
  _avg: DateSlotAvgAggregateOutputType | null
  _sum: DateSlotSumAggregateOutputType | null
  _min: DateSlotMinAggregateOutputType | null
  _max: DateSlotMaxAggregateOutputType | null
}

type GetDateSlotGroupByPayload<T extends DateSlotGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<DateSlotGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof DateSlotGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], DateSlotGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], DateSlotGroupByOutputType[P]>
      }
    >
  >



export type DateSlotWhereInput = {
  AND?: Prisma.DateSlotWhereInput | Prisma.DateSlotWhereInput[]
  OR?: Prisma.DateSlotWhereInput[]
  NOT?: Prisma.DateSlotWhereInput | Prisma.DateSlotWhereInput[]
  id?: Prisma.BigIntFilter<"DateSlot"> | bigint | number
  date?: Prisma.DateTimeFilter<"DateSlot"> | Date | string
  timeSlotId?: Prisma.BigIntFilter<"DateSlot"> | bigint | number
  serviceId?: Prisma.BigIntFilter<"DateSlot"> | bigint | number
  maxCapacity?: Prisma.IntFilter<"DateSlot"> | number
  createdAt?: Prisma.DateTimeFilter<"DateSlot"> | Date | string
  timeSlot?: Prisma.XOR<Prisma.TimeSlotScalarRelationFilter, Prisma.TimeSlotWhereInput>
  service?: Prisma.XOR<Prisma.ServiceScalarRelationFilter, Prisma.ServiceWhereInput>
  bookings?: Prisma.BookingListRelationFilter
}

export type DateSlotOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  date?: Prisma.SortOrder
  timeSlotId?: Prisma.SortOrder
  serviceId?: Prisma.SortOrder
  maxCapacity?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  timeSlot?: Prisma.TimeSlotOrderByWithRelationInput
  service?: Prisma.ServiceOrderByWithRelationInput
  bookings?: Prisma.BookingOrderByRelationAggregateInput
}

export type DateSlotWhereUniqueInput = Prisma.AtLeast<{
  id?: bigint | number
  date_timeSlotId_serviceId?: Prisma.DateSlotDateTimeSlotIdServiceIdCompoundUniqueInput
  AND?: Prisma.DateSlotWhereInput | Prisma.DateSlotWhereInput[]
  OR?: Prisma.DateSlotWhereInput[]
  NOT?: Prisma.DateSlotWhereInput | Prisma.DateSlotWhereInput[]
  date?: Prisma.DateTimeFilter<"DateSlot"> | Date | string
  timeSlotId?: Prisma.BigIntFilter<"DateSlot"> | bigint | number
  serviceId?: Prisma.BigIntFilter<"DateSlot"> | bigint | number
  maxCapacity?: Prisma.IntFilter<"DateSlot"> | number
  createdAt?: Prisma.DateTimeFilter<"DateSlot"> | Date | string
  timeSlot?: Prisma.XOR<Prisma.TimeSlotScalarRelationFilter, Prisma.TimeSlotWhereInput>
  service?: Prisma.XOR<Prisma.ServiceScalarRelationFilter, Prisma.ServiceWhereInput>
  bookings?: Prisma.BookingListRelationFilter
}, "id" | "date_timeSlotId_serviceId">

export type DateSlotOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  date?: Prisma.SortOrder
  timeSlotId?: Prisma.SortOrder
  serviceId?: Prisma.SortOrder
  maxCapacity?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  _count?: Prisma.DateSlotCountOrderByAggregateInput
  _avg?: Prisma.DateSlotAvgOrderByAggregateInput
  _max?: Prisma.DateSlotMaxOrderByAggregateInput
  _min?: Prisma.DateSlotMinOrderByAggregateInput
  _sum?: Prisma.DateSlotSumOrderByAggregateInput
}

export type DateSlotScalarWhereWithAggregatesInput = {
  AND?: Prisma.DateSlotScalarWhereWithAggregatesInput | Prisma.DateSlotScalarWhereWithAggregatesInput[]
  OR?: Prisma.DateSlotScalarWhereWithAggregatesInput[]
  NOT?: Prisma.DateSlotScalarWhereWithAggregatesInput | Prisma.DateSlotScalarWhereWithAggregatesInput[]
  id?: Prisma.BigIntWithAggregatesFilter<"DateSlot"> | bigint | number
  date?: Prisma.DateTimeWithAggregatesFilter<"DateSlot"> | Date | string
  timeSlotId?: Prisma.BigIntWithAggregatesFilter<"DateSlot"> | bigint | number
  serviceId?: Prisma.BigIntWithAggregatesFilter<"DateSlot"> | bigint | number
  maxCapacity?: Prisma.IntWithAggregatesFilter<"DateSlot"> | number
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"DateSlot"> | Date | string
}

export type DateSlotCreateInput = {
  id?: bigint | number
  date: Date | string
  maxCapacity: number
  createdAt?: Date | string
  timeSlot: Prisma.TimeSlotCreateNestedOneWithoutDateSlotsInput
  service: Prisma.ServiceCreateNestedOneWithoutDateSlotsInput
  bookings?: Prisma.BookingCreateNestedManyWithoutDateSlotInput
}

export type DateSlotUncheckedCreateInput = {
  id?: bigint | number
  date: Date | string
  timeSlotId: bigint | number
  serviceId: bigint | number
  maxCapacity: number
  createdAt?: Date | string
  bookings?: Prisma.BookingUncheckedCreateNestedManyWithoutDateSlotInput
}

export type DateSlotUpdateInput = {
  id?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  maxCapacity?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  timeSlot?: Prisma.TimeSlotUpdateOneRequiredWithoutDateSlotsNestedInput
  service?: Prisma.ServiceUpdateOneRequiredWithoutDateSlotsNestedInput
  bookings?: Prisma.BookingUpdateManyWithoutDateSlotNestedInput
}

export type DateSlotUncheckedUpdateInput = {
  id?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  timeSlotId?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  serviceId?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  maxCapacity?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  bookings?: Prisma.BookingUncheckedUpdateManyWithoutDateSlotNestedInput
}

export type DateSlotCreateManyInput = {
  id?: bigint | number
  date: Date | string
  timeSlotId: bigint | number
  serviceId: bigint | number
  maxCapacity: number
  createdAt?: Date | string
}

export type DateSlotUpdateManyMutationInput = {
  id?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  maxCapacity?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type DateSlotUncheckedUpdateManyInput = {
  id?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  timeSlotId?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  serviceId?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  maxCapacity?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type DateSlotListRelationFilter = {
  every?: Prisma.DateSlotWhereInput
  some?: Prisma.DateSlotWhereInput
  none?: Prisma.DateSlotWhereInput
}

export type DateSlotOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type DateSlotDateTimeSlotIdServiceIdCompoundUniqueInput = {
  date: Date | string
  timeSlotId: bigint | number
  serviceId: bigint | number
}

export type DateSlotCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  date?: Prisma.SortOrder
  timeSlotId?: Prisma.SortOrder
  serviceId?: Prisma.SortOrder
  maxCapacity?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type DateSlotAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
  timeSlotId?: Prisma.SortOrder
  serviceId?: Prisma.SortOrder
  maxCapacity?: Prisma.SortOrder
}

export type DateSlotMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  date?: Prisma.SortOrder
  timeSlotId?: Prisma.SortOrder
  serviceId?: Prisma.SortOrder
  maxCapacity?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type DateSlotMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  date?: Prisma.SortOrder
  timeSlotId?: Prisma.SortOrder
  serviceId?: Prisma.SortOrder
  maxCapacity?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type DateSlotSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
  timeSlotId?: Prisma.SortOrder
  serviceId?: Prisma.SortOrder
  maxCapacity?: Prisma.SortOrder
}

export type DateSlotScalarRelationFilter = {
  is?: Prisma.DateSlotWhereInput
  isNot?: Prisma.DateSlotWhereInput
}

export type DateSlotCreateNestedManyWithoutServiceInput = {
  create?: Prisma.XOR<Prisma.DateSlotCreateWithoutServiceInput, Prisma.DateSlotUncheckedCreateWithoutServiceInput> | Prisma.DateSlotCreateWithoutServiceInput[] | Prisma.DateSlotUncheckedCreateWithoutServiceInput[]
  connectOrCreate?: Prisma.DateSlotCreateOrConnectWithoutServiceInput | Prisma.DateSlotCreateOrConnectWithoutServiceInput[]
  createMany?: Prisma.DateSlotCreateManyServiceInputEnvelope
  connect?: Prisma.DateSlotWhereUniqueInput | Prisma.DateSlotWhereUniqueInput[]
}

export type DateSlotUncheckedCreateNestedManyWithoutServiceInput = {
  create?: Prisma.XOR<Prisma.DateSlotCreateWithoutServiceInput, Prisma.DateSlotUncheckedCreateWithoutServiceInput> | Prisma.DateSlotCreateWithoutServiceInput[] | Prisma.DateSlotUncheckedCreateWithoutServiceInput[]
  connectOrCreate?: Prisma.DateSlotCreateOrConnectWithoutServiceInput | Prisma.DateSlotCreateOrConnectWithoutServiceInput[]
  createMany?: Prisma.DateSlotCreateManyServiceInputEnvelope
  connect?: Prisma.DateSlotWhereUniqueInput | Prisma.DateSlotWhereUniqueInput[]
}

export type DateSlotUpdateManyWithoutServiceNestedInput = {
  create?: Prisma.XOR<Prisma.DateSlotCreateWithoutServiceInput, Prisma.DateSlotUncheckedCreateWithoutServiceInput> | Prisma.DateSlotCreateWithoutServiceInput[] | Prisma.DateSlotUncheckedCreateWithoutServiceInput[]
  connectOrCreate?: Prisma.DateSlotCreateOrConnectWithoutServiceInput | Prisma.DateSlotCreateOrConnectWithoutServiceInput[]
  upsert?: Prisma.DateSlotUpsertWithWhereUniqueWithoutServiceInput | Prisma.DateSlotUpsertWithWhereUniqueWithoutServiceInput[]
  createMany?: Prisma.DateSlotCreateManyServiceInputEnvelope
  set?: Prisma.DateSlotWhereUniqueInput | Prisma.DateSlotWhereUniqueInput[]
  disconnect?: Prisma.DateSlotWhereUniqueInput | Prisma.DateSlotWhereUniqueInput[]
  delete?: Prisma.DateSlotWhereUniqueInput | Prisma.DateSlotWhereUniqueInput[]
  connect?: Prisma.DateSlotWhereUniqueInput | Prisma.DateSlotWhereUniqueInput[]
  update?: Prisma.DateSlotUpdateWithWhereUniqueWithoutServiceInput | Prisma.DateSlotUpdateWithWhereUniqueWithoutServiceInput[]
  updateMany?: Prisma.DateSlotUpdateManyWithWhereWithoutServiceInput | Prisma.DateSlotUpdateManyWithWhereWithoutServiceInput[]
  deleteMany?: Prisma.DateSlotScalarWhereInput | Prisma.DateSlotScalarWhereInput[]
}

export type DateSlotUncheckedUpdateManyWithoutServiceNestedInput = {
  create?: Prisma.XOR<Prisma.DateSlotCreateWithoutServiceInput, Prisma.DateSlotUncheckedCreateWithoutServiceInput> | Prisma.DateSlotCreateWithoutServiceInput[] | Prisma.DateSlotUncheckedCreateWithoutServiceInput[]
  connectOrCreate?: Prisma.DateSlotCreateOrConnectWithoutServiceInput | Prisma.DateSlotCreateOrConnectWithoutServiceInput[]
  upsert?: Prisma.DateSlotUpsertWithWhereUniqueWithoutServiceInput | Prisma.DateSlotUpsertWithWhereUniqueWithoutServiceInput[]
  createMany?: Prisma.DateSlotCreateManyServiceInputEnvelope
  set?: Prisma.DateSlotWhereUniqueInput | Prisma.DateSlotWhereUniqueInput[]
  disconnect?: Prisma.DateSlotWhereUniqueInput | Prisma.DateSlotWhereUniqueInput[]
  delete?: Prisma.DateSlotWhereUniqueInput | Prisma.DateSlotWhereUniqueInput[]
  connect?: Prisma.DateSlotWhereUniqueInput | Prisma.DateSlotWhereUniqueInput[]
  update?: Prisma.DateSlotUpdateWithWhereUniqueWithoutServiceInput | Prisma.DateSlotUpdateWithWhereUniqueWithoutServiceInput[]
  updateMany?: Prisma.DateSlotUpdateManyWithWhereWithoutServiceInput | Prisma.DateSlotUpdateManyWithWhereWithoutServiceInput[]
  deleteMany?: Prisma.DateSlotScalarWhereInput | Prisma.DateSlotScalarWhereInput[]
}

export type DateSlotCreateNestedManyWithoutTimeSlotInput = {
  create?: Prisma.XOR<Prisma.DateSlotCreateWithoutTimeSlotInput, Prisma.DateSlotUncheckedCreateWithoutTimeSlotInput> | Prisma.DateSlotCreateWithoutTimeSlotInput[] | Prisma.DateSlotUncheckedCreateWithoutTimeSlotInput[]
  connectOrCreate?: Prisma.DateSlotCreateOrConnectWithoutTimeSlotInput | Prisma.DateSlotCreateOrConnectWithoutTimeSlotInput[]
  createMany?: Prisma.DateSlotCreateManyTimeSlotInputEnvelope
  connect?: Prisma.DateSlotWhereUniqueInput | Prisma.DateSlotWhereUniqueInput[]
}

export type DateSlotUncheckedCreateNestedManyWithoutTimeSlotInput = {
  create?: Prisma.XOR<Prisma.DateSlotCreateWithoutTimeSlotInput, Prisma.DateSlotUncheckedCreateWithoutTimeSlotInput> | Prisma.DateSlotCreateWithoutTimeSlotInput[] | Prisma.DateSlotUncheckedCreateWithoutTimeSlotInput[]
  connectOrCreate?: Prisma.DateSlotCreateOrConnectWithoutTimeSlotInput | Prisma.DateSlotCreateOrConnectWithoutTimeSlotInput[]
  createMany?: Prisma.DateSlotCreateManyTimeSlotInputEnvelope
  connect?: Prisma.DateSlotWhereUniqueInput | Prisma.DateSlotWhereUniqueInput[]
}

export type DateSlotUpdateManyWithoutTimeSlotNestedInput = {
  create?: Prisma.XOR<Prisma.DateSlotCreateWithoutTimeSlotInput, Prisma.DateSlotUncheckedCreateWithoutTimeSlotInput> | Prisma.DateSlotCreateWithoutTimeSlotInput[] | Prisma.DateSlotUncheckedCreateWithoutTimeSlotInput[]
  connectOrCreate?: Prisma.DateSlotCreateOrConnectWithoutTimeSlotInput | Prisma.DateSlotCreateOrConnectWithoutTimeSlotInput[]
  upsert?: Prisma.DateSlotUpsertWithWhereUniqueWithoutTimeSlotInput | Prisma.DateSlotUpsertWithWhereUniqueWithoutTimeSlotInput[]
  createMany?: Prisma.DateSlotCreateManyTimeSlotInputEnvelope
  set?: Prisma.DateSlotWhereUniqueInput | Prisma.DateSlotWhereUniqueInput[]
  disconnect?: Prisma.DateSlotWhereUniqueInput | Prisma.DateSlotWhereUniqueInput[]
  delete?: Prisma.DateSlotWhereUniqueInput | Prisma.DateSlotWhereUniqueInput[]
  connect?: Prisma.DateSlotWhereUniqueInput | Prisma.DateSlotWhereUniqueInput[]
  update?: Prisma.DateSlotUpdateWithWhereUniqueWithoutTimeSlotInput | Prisma.DateSlotUpdateWithWhereUniqueWithoutTimeSlotInput[]
  updateMany?: Prisma.DateSlotUpdateManyWithWhereWithoutTimeSlotInput | Prisma.DateSlotUpdateManyWithWhereWithoutTimeSlotInput[]
  deleteMany?: Prisma.DateSlotScalarWhereInput | Prisma.DateSlotScalarWhereInput[]
}

export type DateSlotUncheckedUpdateManyWithoutTimeSlotNestedInput = {
  create?: Prisma.XOR<Prisma.DateSlotCreateWithoutTimeSlotInput, Prisma.DateSlotUncheckedCreateWithoutTimeSlotInput> | Prisma.DateSlotCreateWithoutTimeSlotInput[] | Prisma.DateSlotUncheckedCreateWithoutTimeSlotInput[]
  connectOrCreate?: Prisma.DateSlotCreateOrConnectWithoutTimeSlotInput | Prisma.DateSlotCreateOrConnectWithoutTimeSlotInput[]
  upsert?: Prisma.DateSlotUpsertWithWhereUniqueWithoutTimeSlotInput | Prisma.DateSlotUpsertWithWhereUniqueWithoutTimeSlotInput[]
  createMany?: Prisma.DateSlotCreateManyTimeSlotInputEnvelope
  set?: Prisma.DateSlotWhereUniqueInput | Prisma.DateSlotWhereUniqueInput[]
  disconnect?: Prisma.DateSlotWhereUniqueInput | Prisma.DateSlotWhereUniqueInput[]
  delete?: Prisma.DateSlotWhereUniqueInput | Prisma.DateSlotWhereUniqueInput[]
  connect?: Prisma.DateSlotWhereUniqueInput | Prisma.DateSlotWhereUniqueInput[]
  update?: Prisma.DateSlotUpdateWithWhereUniqueWithoutTimeSlotInput | Prisma.DateSlotUpdateWithWhereUniqueWithoutTimeSlotInput[]
  updateMany?: Prisma.DateSlotUpdateManyWithWhereWithoutTimeSlotInput | Prisma.DateSlotUpdateManyWithWhereWithoutTimeSlotInput[]
  deleteMany?: Prisma.DateSlotScalarWhereInput | Prisma.DateSlotScalarWhereInput[]
}

export type DateSlotCreateNestedOneWithoutBookingsInput = {
  create?: Prisma.XOR<Prisma.DateSlotCreateWithoutBookingsInput, Prisma.DateSlotUncheckedCreateWithoutBookingsInput>
  connectOrCreate?: Prisma.DateSlotCreateOrConnectWithoutBookingsInput
  connect?: Prisma.DateSlotWhereUniqueInput
}

export type DateSlotUpdateOneRequiredWithoutBookingsNestedInput = {
  create?: Prisma.XOR<Prisma.DateSlotCreateWithoutBookingsInput, Prisma.DateSlotUncheckedCreateWithoutBookingsInput>
  connectOrCreate?: Prisma.DateSlotCreateOrConnectWithoutBookingsInput
  upsert?: Prisma.DateSlotUpsertWithoutBookingsInput
  connect?: Prisma.DateSlotWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.DateSlotUpdateToOneWithWhereWithoutBookingsInput, Prisma.DateSlotUpdateWithoutBookingsInput>, Prisma.DateSlotUncheckedUpdateWithoutBookingsInput>
}

export type DateSlotCreateWithoutServiceInput = {
  id?: bigint | number
  date: Date | string
  maxCapacity: number
  createdAt?: Date | string
  timeSlot: Prisma.TimeSlotCreateNestedOneWithoutDateSlotsInput
  bookings?: Prisma.BookingCreateNestedManyWithoutDateSlotInput
}

export type DateSlotUncheckedCreateWithoutServiceInput = {
  id?: bigint | number
  date: Date | string
  timeSlotId: bigint | number
  maxCapacity: number
  createdAt?: Date | string
  bookings?: Prisma.BookingUncheckedCreateNestedManyWithoutDateSlotInput
}

export type DateSlotCreateOrConnectWithoutServiceInput = {
  where: Prisma.DateSlotWhereUniqueInput
  create: Prisma.XOR<Prisma.DateSlotCreateWithoutServiceInput, Prisma.DateSlotUncheckedCreateWithoutServiceInput>
}

export type DateSlotCreateManyServiceInputEnvelope = {
  data: Prisma.DateSlotCreateManyServiceInput | Prisma.DateSlotCreateManyServiceInput[]
  skipDuplicates?: boolean
}

export type DateSlotUpsertWithWhereUniqueWithoutServiceInput = {
  where: Prisma.DateSlotWhereUniqueInput
  update: Prisma.XOR<Prisma.DateSlotUpdateWithoutServiceInput, Prisma.DateSlotUncheckedUpdateWithoutServiceInput>
  create: Prisma.XOR<Prisma.DateSlotCreateWithoutServiceInput, Prisma.DateSlotUncheckedCreateWithoutServiceInput>
}

export type DateSlotUpdateWithWhereUniqueWithoutServiceInput = {
  where: Prisma.DateSlotWhereUniqueInput
  data: Prisma.XOR<Prisma.DateSlotUpdateWithoutServiceInput, Prisma.DateSlotUncheckedUpdateWithoutServiceInput>
}

export type DateSlotUpdateManyWithWhereWithoutServiceInput = {
  where: Prisma.DateSlotScalarWhereInput
  data: Prisma.XOR<Prisma.DateSlotUpdateManyMutationInput, Prisma.DateSlotUncheckedUpdateManyWithoutServiceInput>
}

export type DateSlotScalarWhereInput = {
  AND?: Prisma.DateSlotScalarWhereInput | Prisma.DateSlotScalarWhereInput[]
  OR?: Prisma.DateSlotScalarWhereInput[]
  NOT?: Prisma.DateSlotScalarWhereInput | Prisma.DateSlotScalarWhereInput[]
  id?: Prisma.BigIntFilter<"DateSlot"> | bigint | number
  date?: Prisma.DateTimeFilter<"DateSlot"> | Date | string
  timeSlotId?: Prisma.BigIntFilter<"DateSlot"> | bigint | number
  serviceId?: Prisma.BigIntFilter<"DateSlot"> | bigint | number
  maxCapacity?: Prisma.IntFilter<"DateSlot"> | number
  createdAt?: Prisma.DateTimeFilter<"DateSlot"> | Date | string
}

export type DateSlotCreateWithoutTimeSlotInput = {
  id?: bigint | number
  date: Date | string
  maxCapacity: number
  createdAt?: Date | string
  service: Prisma.ServiceCreateNestedOneWithoutDateSlotsInput
  bookings?: Prisma.BookingCreateNestedManyWithoutDateSlotInput
}

export type DateSlotUncheckedCreateWithoutTimeSlotInput = {
  id?: bigint | number
  date: Date | string
  serviceId: bigint | number
  maxCapacity: number
  createdAt?: Date | string
  bookings?: Prisma.BookingUncheckedCreateNestedManyWithoutDateSlotInput
}

export type DateSlotCreateOrConnectWithoutTimeSlotInput = {
  where: Prisma.DateSlotWhereUniqueInput
  create: Prisma.XOR<Prisma.DateSlotCreateWithoutTimeSlotInput, Prisma.DateSlotUncheckedCreateWithoutTimeSlotInput>
}

export type DateSlotCreateManyTimeSlotInputEnvelope = {
  data: Prisma.DateSlotCreateManyTimeSlotInput | Prisma.DateSlotCreateManyTimeSlotInput[]
  skipDuplicates?: boolean
}

export type DateSlotUpsertWithWhereUniqueWithoutTimeSlotInput = {
  where: Prisma.DateSlotWhereUniqueInput
  update: Prisma.XOR<Prisma.DateSlotUpdateWithoutTimeSlotInput, Prisma.DateSlotUncheckedUpdateWithoutTimeSlotInput>
  create: Prisma.XOR<Prisma.DateSlotCreateWithoutTimeSlotInput, Prisma.DateSlotUncheckedCreateWithoutTimeSlotInput>
}

export type DateSlotUpdateWithWhereUniqueWithoutTimeSlotInput = {
  where: Prisma.DateSlotWhereUniqueInput
  data: Prisma.XOR<Prisma.DateSlotUpdateWithoutTimeSlotInput, Prisma.DateSlotUncheckedUpdateWithoutTimeSlotInput>
}

export type DateSlotUpdateManyWithWhereWithoutTimeSlotInput = {
  where: Prisma.DateSlotScalarWhereInput
  data: Prisma.XOR<Prisma.DateSlotUpdateManyMutationInput, Prisma.DateSlotUncheckedUpdateManyWithoutTimeSlotInput>
}

export type DateSlotCreateWithoutBookingsInput = {
  id?: bigint | number
  date: Date | string
  maxCapacity: number
  createdAt?: Date | string
  timeSlot: Prisma.TimeSlotCreateNestedOneWithoutDateSlotsInput
  service: Prisma.ServiceCreateNestedOneWithoutDateSlotsInput
}

export type DateSlotUncheckedCreateWithoutBookingsInput = {
  id?: bigint | number
  date: Date | string
  timeSlotId: bigint | number
  serviceId: bigint | number
  maxCapacity: number
  createdAt?: Date | string
}

export type DateSlotCreateOrConnectWithoutBookingsInput = {
  where: Prisma.DateSlotWhereUniqueInput
  create: Prisma.XOR<Prisma.DateSlotCreateWithoutBookingsInput, Prisma.DateSlotUncheckedCreateWithoutBookingsInput>
}

export type DateSlotUpsertWithoutBookingsInput = {
  update: Prisma.XOR<Prisma.DateSlotUpdateWithoutBookingsInput, Prisma.DateSlotUncheckedUpdateWithoutBookingsInput>
  create: Prisma.XOR<Prisma.DateSlotCreateWithoutBookingsInput, Prisma.DateSlotUncheckedCreateWithoutBookingsInput>
  where?: Prisma.DateSlotWhereInput
}

export type DateSlotUpdateToOneWithWhereWithoutBookingsInput = {
  where?: Prisma.DateSlotWhereInput
  data: Prisma.XOR<Prisma.DateSlotUpdateWithoutBookingsInput, Prisma.DateSlotUncheckedUpdateWithoutBookingsInput>
}

export type DateSlotUpdateWithoutBookingsInput = {
  id?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  maxCapacity?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  timeSlot?: Prisma.TimeSlotUpdateOneRequiredWithoutDateSlotsNestedInput
  service?: Prisma.ServiceUpdateOneRequiredWithoutDateSlotsNestedInput
}

export type DateSlotUncheckedUpdateWithoutBookingsInput = {
  id?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  timeSlotId?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  serviceId?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  maxCapacity?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type DateSlotCreateManyServiceInput = {
  id?: bigint | number
  date: Date | string
  timeSlotId: bigint | number
  maxCapacity: number
  createdAt?: Date | string
}

export type DateSlotUpdateWithoutServiceInput = {
  id?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  maxCapacity?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  timeSlot?: Prisma.TimeSlotUpdateOneRequiredWithoutDateSlotsNestedInput
  bookings?: Prisma.BookingUpdateManyWithoutDateSlotNestedInput
}

export type DateSlotUncheckedUpdateWithoutServiceInput = {
  id?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  timeSlotId?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  maxCapacity?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  bookings?: Prisma.BookingUncheckedUpdateManyWithoutDateSlotNestedInput
}

export type DateSlotUncheckedUpdateManyWithoutServiceInput = {
  id?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  timeSlotId?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  maxCapacity?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type DateSlotCreateManyTimeSlotInput = {
  id?: bigint | number
  date: Date | string
  serviceId: bigint | number
  maxCapacity: number
  createdAt?: Date | string
}

export type DateSlotUpdateWithoutTimeSlotInput = {
  id?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  maxCapacity?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  service?: Prisma.ServiceUpdateOneRequiredWithoutDateSlotsNestedInput
  bookings?: Prisma.BookingUpdateManyWithoutDateSlotNestedInput
}

export type DateSlotUncheckedUpdateWithoutTimeSlotInput = {
  id?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  serviceId?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  maxCapacity?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  bookings?: Prisma.BookingUncheckedUpdateManyWithoutDateSlotNestedInput
}

export type DateSlotUncheckedUpdateManyWithoutTimeSlotInput = {
  id?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  serviceId?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  maxCapacity?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}


/**
 * Count Type DateSlotCountOutputType
 */

export type DateSlotCountOutputType = {
  bookings: number
}

export type DateSlotCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  bookings?: boolean | DateSlotCountOutputTypeCountBookingsArgs
}

/**
 * DateSlotCountOutputType without action
 */
export type DateSlotCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DateSlotCountOutputType
   */
  select?: Prisma.DateSlotCountOutputTypeSelect<ExtArgs> | null
}

/**
 * DateSlotCountOutputType without action
 */
export type DateSlotCountOutputTypeCountBookingsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.BookingWhereInput
}


export type DateSlotSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  date?: boolean
  timeSlotId?: boolean
  serviceId?: boolean
  maxCapacity?: boolean
  createdAt?: boolean
  timeSlot?: boolean | Prisma.TimeSlotDefaultArgs<ExtArgs>
  service?: boolean | Prisma.ServiceDefaultArgs<ExtArgs>
  bookings?: boolean | Prisma.DateSlot$bookingsArgs<ExtArgs>
  _count?: boolean | Prisma.DateSlotCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["dateSlot"]>



export type DateSlotSelectScalar = {
  id?: boolean
  date?: boolean
  timeSlotId?: boolean
  serviceId?: boolean
  maxCapacity?: boolean
  createdAt?: boolean
}

export type DateSlotOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "date" | "timeSlotId" | "serviceId" | "maxCapacity" | "createdAt", ExtArgs["result"]["dateSlot"]>
export type DateSlotInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  timeSlot?: boolean | Prisma.TimeSlotDefaultArgs<ExtArgs>
  service?: boolean | Prisma.ServiceDefaultArgs<ExtArgs>
  bookings?: boolean | Prisma.DateSlot$bookingsArgs<ExtArgs>
  _count?: boolean | Prisma.DateSlotCountOutputTypeDefaultArgs<ExtArgs>
}

export type $DateSlotPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "DateSlot"
  objects: {
    timeSlot: Prisma.$TimeSlotPayload<ExtArgs>
    service: Prisma.$ServicePayload<ExtArgs>
    bookings: Prisma.$BookingPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: bigint
    date: Date
    timeSlotId: bigint
    serviceId: bigint
    maxCapacity: number
    createdAt: Date
  }, ExtArgs["result"]["dateSlot"]>
  composites: {}
}

export type DateSlotGetPayload<S extends boolean | null | undefined | DateSlotDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$DateSlotPayload, S>

export type DateSlotCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<DateSlotFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: DateSlotCountAggregateInputType | true
  }

export interface DateSlotDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['DateSlot'], meta: { name: 'DateSlot' } }
  /**
   * Find zero or one DateSlot that matches the filter.
   * @param {DateSlotFindUniqueArgs} args - Arguments to find a DateSlot
   * @example
   * // Get one DateSlot
   * const dateSlot = await prisma.dateSlot.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends DateSlotFindUniqueArgs>(args: Prisma.SelectSubset<T, DateSlotFindUniqueArgs<ExtArgs>>): Prisma.Prisma__DateSlotClient<runtime.Types.Result.GetResult<Prisma.$DateSlotPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one DateSlot that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {DateSlotFindUniqueOrThrowArgs} args - Arguments to find a DateSlot
   * @example
   * // Get one DateSlot
   * const dateSlot = await prisma.dateSlot.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends DateSlotFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, DateSlotFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__DateSlotClient<runtime.Types.Result.GetResult<Prisma.$DateSlotPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first DateSlot that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DateSlotFindFirstArgs} args - Arguments to find a DateSlot
   * @example
   * // Get one DateSlot
   * const dateSlot = await prisma.dateSlot.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends DateSlotFindFirstArgs>(args?: Prisma.SelectSubset<T, DateSlotFindFirstArgs<ExtArgs>>): Prisma.Prisma__DateSlotClient<runtime.Types.Result.GetResult<Prisma.$DateSlotPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first DateSlot that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DateSlotFindFirstOrThrowArgs} args - Arguments to find a DateSlot
   * @example
   * // Get one DateSlot
   * const dateSlot = await prisma.dateSlot.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends DateSlotFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, DateSlotFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__DateSlotClient<runtime.Types.Result.GetResult<Prisma.$DateSlotPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more DateSlots that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DateSlotFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all DateSlots
   * const dateSlots = await prisma.dateSlot.findMany()
   * 
   * // Get first 10 DateSlots
   * const dateSlots = await prisma.dateSlot.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const dateSlotWithIdOnly = await prisma.dateSlot.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends DateSlotFindManyArgs>(args?: Prisma.SelectSubset<T, DateSlotFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$DateSlotPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a DateSlot.
   * @param {DateSlotCreateArgs} args - Arguments to create a DateSlot.
   * @example
   * // Create one DateSlot
   * const DateSlot = await prisma.dateSlot.create({
   *   data: {
   *     // ... data to create a DateSlot
   *   }
   * })
   * 
   */
  create<T extends DateSlotCreateArgs>(args: Prisma.SelectSubset<T, DateSlotCreateArgs<ExtArgs>>): Prisma.Prisma__DateSlotClient<runtime.Types.Result.GetResult<Prisma.$DateSlotPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many DateSlots.
   * @param {DateSlotCreateManyArgs} args - Arguments to create many DateSlots.
   * @example
   * // Create many DateSlots
   * const dateSlot = await prisma.dateSlot.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends DateSlotCreateManyArgs>(args?: Prisma.SelectSubset<T, DateSlotCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Delete a DateSlot.
   * @param {DateSlotDeleteArgs} args - Arguments to delete one DateSlot.
   * @example
   * // Delete one DateSlot
   * const DateSlot = await prisma.dateSlot.delete({
   *   where: {
   *     // ... filter to delete one DateSlot
   *   }
   * })
   * 
   */
  delete<T extends DateSlotDeleteArgs>(args: Prisma.SelectSubset<T, DateSlotDeleteArgs<ExtArgs>>): Prisma.Prisma__DateSlotClient<runtime.Types.Result.GetResult<Prisma.$DateSlotPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one DateSlot.
   * @param {DateSlotUpdateArgs} args - Arguments to update one DateSlot.
   * @example
   * // Update one DateSlot
   * const dateSlot = await prisma.dateSlot.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends DateSlotUpdateArgs>(args: Prisma.SelectSubset<T, DateSlotUpdateArgs<ExtArgs>>): Prisma.Prisma__DateSlotClient<runtime.Types.Result.GetResult<Prisma.$DateSlotPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more DateSlots.
   * @param {DateSlotDeleteManyArgs} args - Arguments to filter DateSlots to delete.
   * @example
   * // Delete a few DateSlots
   * const { count } = await prisma.dateSlot.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends DateSlotDeleteManyArgs>(args?: Prisma.SelectSubset<T, DateSlotDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more DateSlots.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DateSlotUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many DateSlots
   * const dateSlot = await prisma.dateSlot.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends DateSlotUpdateManyArgs>(args: Prisma.SelectSubset<T, DateSlotUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create or update one DateSlot.
   * @param {DateSlotUpsertArgs} args - Arguments to update or create a DateSlot.
   * @example
   * // Update or create a DateSlot
   * const dateSlot = await prisma.dateSlot.upsert({
   *   create: {
   *     // ... data to create a DateSlot
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the DateSlot we want to update
   *   }
   * })
   */
  upsert<T extends DateSlotUpsertArgs>(args: Prisma.SelectSubset<T, DateSlotUpsertArgs<ExtArgs>>): Prisma.Prisma__DateSlotClient<runtime.Types.Result.GetResult<Prisma.$DateSlotPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of DateSlots.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DateSlotCountArgs} args - Arguments to filter DateSlots to count.
   * @example
   * // Count the number of DateSlots
   * const count = await prisma.dateSlot.count({
   *   where: {
   *     // ... the filter for the DateSlots we want to count
   *   }
   * })
  **/
  count<T extends DateSlotCountArgs>(
    args?: Prisma.Subset<T, DateSlotCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], DateSlotCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a DateSlot.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DateSlotAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends DateSlotAggregateArgs>(args: Prisma.Subset<T, DateSlotAggregateArgs>): Prisma.PrismaPromise<GetDateSlotAggregateType<T>>

  /**
   * Group by DateSlot.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DateSlotGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends DateSlotGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: DateSlotGroupByArgs['orderBy'] }
      : { orderBy?: DateSlotGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, DateSlotGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetDateSlotGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the DateSlot model
 */
readonly fields: DateSlotFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for DateSlot.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__DateSlotClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  timeSlot<T extends Prisma.TimeSlotDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.TimeSlotDefaultArgs<ExtArgs>>): Prisma.Prisma__TimeSlotClient<runtime.Types.Result.GetResult<Prisma.$TimeSlotPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  service<T extends Prisma.ServiceDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ServiceDefaultArgs<ExtArgs>>): Prisma.Prisma__ServiceClient<runtime.Types.Result.GetResult<Prisma.$ServicePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  bookings<T extends Prisma.DateSlot$bookingsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.DateSlot$bookingsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$BookingPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the DateSlot model
 */
export interface DateSlotFieldRefs {
  readonly id: Prisma.FieldRef<"DateSlot", 'BigInt'>
  readonly date: Prisma.FieldRef<"DateSlot", 'DateTime'>
  readonly timeSlotId: Prisma.FieldRef<"DateSlot", 'BigInt'>
  readonly serviceId: Prisma.FieldRef<"DateSlot", 'BigInt'>
  readonly maxCapacity: Prisma.FieldRef<"DateSlot", 'Int'>
  readonly createdAt: Prisma.FieldRef<"DateSlot", 'DateTime'>
}
    

// Custom InputTypes
/**
 * DateSlot findUnique
 */
export type DateSlotFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DateSlot
   */
  select?: Prisma.DateSlotSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DateSlot
   */
  omit?: Prisma.DateSlotOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DateSlotInclude<ExtArgs> | null
  /**
   * Filter, which DateSlot to fetch.
   */
  where: Prisma.DateSlotWhereUniqueInput
}

/**
 * DateSlot findUniqueOrThrow
 */
export type DateSlotFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DateSlot
   */
  select?: Prisma.DateSlotSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DateSlot
   */
  omit?: Prisma.DateSlotOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DateSlotInclude<ExtArgs> | null
  /**
   * Filter, which DateSlot to fetch.
   */
  where: Prisma.DateSlotWhereUniqueInput
}

/**
 * DateSlot findFirst
 */
export type DateSlotFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DateSlot
   */
  select?: Prisma.DateSlotSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DateSlot
   */
  omit?: Prisma.DateSlotOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DateSlotInclude<ExtArgs> | null
  /**
   * Filter, which DateSlot to fetch.
   */
  where?: Prisma.DateSlotWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of DateSlots to fetch.
   */
  orderBy?: Prisma.DateSlotOrderByWithRelationInput | Prisma.DateSlotOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for DateSlots.
   */
  cursor?: Prisma.DateSlotWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` DateSlots from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` DateSlots.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of DateSlots.
   */
  distinct?: Prisma.DateSlotScalarFieldEnum | Prisma.DateSlotScalarFieldEnum[]
}

/**
 * DateSlot findFirstOrThrow
 */
export type DateSlotFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DateSlot
   */
  select?: Prisma.DateSlotSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DateSlot
   */
  omit?: Prisma.DateSlotOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DateSlotInclude<ExtArgs> | null
  /**
   * Filter, which DateSlot to fetch.
   */
  where?: Prisma.DateSlotWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of DateSlots to fetch.
   */
  orderBy?: Prisma.DateSlotOrderByWithRelationInput | Prisma.DateSlotOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for DateSlots.
   */
  cursor?: Prisma.DateSlotWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` DateSlots from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` DateSlots.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of DateSlots.
   */
  distinct?: Prisma.DateSlotScalarFieldEnum | Prisma.DateSlotScalarFieldEnum[]
}

/**
 * DateSlot findMany
 */
export type DateSlotFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DateSlot
   */
  select?: Prisma.DateSlotSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DateSlot
   */
  omit?: Prisma.DateSlotOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DateSlotInclude<ExtArgs> | null
  /**
   * Filter, which DateSlots to fetch.
   */
  where?: Prisma.DateSlotWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of DateSlots to fetch.
   */
  orderBy?: Prisma.DateSlotOrderByWithRelationInput | Prisma.DateSlotOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing DateSlots.
   */
  cursor?: Prisma.DateSlotWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` DateSlots from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` DateSlots.
   */
  skip?: number
  distinct?: Prisma.DateSlotScalarFieldEnum | Prisma.DateSlotScalarFieldEnum[]
}

/**
 * DateSlot create
 */
export type DateSlotCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DateSlot
   */
  select?: Prisma.DateSlotSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DateSlot
   */
  omit?: Prisma.DateSlotOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DateSlotInclude<ExtArgs> | null
  /**
   * The data needed to create a DateSlot.
   */
  data: Prisma.XOR<Prisma.DateSlotCreateInput, Prisma.DateSlotUncheckedCreateInput>
}

/**
 * DateSlot createMany
 */
export type DateSlotCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many DateSlots.
   */
  data: Prisma.DateSlotCreateManyInput | Prisma.DateSlotCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * DateSlot update
 */
export type DateSlotUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DateSlot
   */
  select?: Prisma.DateSlotSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DateSlot
   */
  omit?: Prisma.DateSlotOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DateSlotInclude<ExtArgs> | null
  /**
   * The data needed to update a DateSlot.
   */
  data: Prisma.XOR<Prisma.DateSlotUpdateInput, Prisma.DateSlotUncheckedUpdateInput>
  /**
   * Choose, which DateSlot to update.
   */
  where: Prisma.DateSlotWhereUniqueInput
}

/**
 * DateSlot updateMany
 */
export type DateSlotUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update DateSlots.
   */
  data: Prisma.XOR<Prisma.DateSlotUpdateManyMutationInput, Prisma.DateSlotUncheckedUpdateManyInput>
  /**
   * Filter which DateSlots to update
   */
  where?: Prisma.DateSlotWhereInput
  /**
   * Limit how many DateSlots to update.
   */
  limit?: number
}

/**
 * DateSlot upsert
 */
export type DateSlotUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DateSlot
   */
  select?: Prisma.DateSlotSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DateSlot
   */
  omit?: Prisma.DateSlotOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DateSlotInclude<ExtArgs> | null
  /**
   * The filter to search for the DateSlot to update in case it exists.
   */
  where: Prisma.DateSlotWhereUniqueInput
  /**
   * In case the DateSlot found by the `where` argument doesn't exist, create a new DateSlot with this data.
   */
  create: Prisma.XOR<Prisma.DateSlotCreateInput, Prisma.DateSlotUncheckedCreateInput>
  /**
   * In case the DateSlot was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.DateSlotUpdateInput, Prisma.DateSlotUncheckedUpdateInput>
}

/**
 * DateSlot delete
 */
export type DateSlotDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DateSlot
   */
  select?: Prisma.DateSlotSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DateSlot
   */
  omit?: Prisma.DateSlotOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DateSlotInclude<ExtArgs> | null
  /**
   * Filter which DateSlot to delete.
   */
  where: Prisma.DateSlotWhereUniqueInput
}

/**
 * DateSlot deleteMany
 */
export type DateSlotDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which DateSlots to delete
   */
  where?: Prisma.DateSlotWhereInput
  /**
   * Limit how many DateSlots to delete.
   */
  limit?: number
}

/**
 * DateSlot.bookings
 */
export type DateSlot$bookingsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Booking
   */
  select?: Prisma.BookingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Booking
   */
  omit?: Prisma.BookingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BookingInclude<ExtArgs> | null
  where?: Prisma.BookingWhereInput
  orderBy?: Prisma.BookingOrderByWithRelationInput | Prisma.BookingOrderByWithRelationInput[]
  cursor?: Prisma.BookingWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.BookingScalarFieldEnum | Prisma.BookingScalarFieldEnum[]
}

/**
 * DateSlot without action
 */
export type DateSlotDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DateSlot
   */
  select?: Prisma.DateSlotSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DateSlot
   */
  omit?: Prisma.DateSlotOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DateSlotInclude<ExtArgs> | null
}
