
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `ServiceFeature` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model ServiceFeature
 * 
 */
export type ServiceFeatureModel = runtime.Types.Result.DefaultSelection<Prisma.$ServiceFeaturePayload>

export type AggregateServiceFeature = {
  _count: ServiceFeatureCountAggregateOutputType | null
  _avg: ServiceFeatureAvgAggregateOutputType | null
  _sum: ServiceFeatureSumAggregateOutputType | null
  _min: ServiceFeatureMinAggregateOutputType | null
  _max: ServiceFeatureMaxAggregateOutputType | null
}

export type ServiceFeatureAvgAggregateOutputType = {
  id: number | null
}

export type ServiceFeatureSumAggregateOutputType = {
  id: number | null
}

export type ServiceFeatureMinAggregateOutputType = {
  id: number | null
  name: string | null
  createdAt: Date | null
  deletedAt: Date | null
}

export type ServiceFeatureMaxAggregateOutputType = {
  id: number | null
  name: string | null
  createdAt: Date | null
  deletedAt: Date | null
}

export type ServiceFeatureCountAggregateOutputType = {
  id: number
  name: number
  createdAt: number
  deletedAt: number
  _all: number
}


export type ServiceFeatureAvgAggregateInputType = {
  id?: true
}

export type ServiceFeatureSumAggregateInputType = {
  id?: true
}

export type ServiceFeatureMinAggregateInputType = {
  id?: true
  name?: true
  createdAt?: true
  deletedAt?: true
}

export type ServiceFeatureMaxAggregateInputType = {
  id?: true
  name?: true
  createdAt?: true
  deletedAt?: true
}

export type ServiceFeatureCountAggregateInputType = {
  id?: true
  name?: true
  createdAt?: true
  deletedAt?: true
  _all?: true
}

export type ServiceFeatureAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ServiceFeature to aggregate.
   */
  where?: Prisma.ServiceFeatureWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ServiceFeatures to fetch.
   */
  orderBy?: Prisma.ServiceFeatureOrderByWithRelationInput | Prisma.ServiceFeatureOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.ServiceFeatureWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ServiceFeatures from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ServiceFeatures.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned ServiceFeatures
  **/
  _count?: true | ServiceFeatureCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: ServiceFeatureAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: ServiceFeatureSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: ServiceFeatureMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: ServiceFeatureMaxAggregateInputType
}

export type GetServiceFeatureAggregateType<T extends ServiceFeatureAggregateArgs> = {
      [P in keyof T & keyof AggregateServiceFeature]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateServiceFeature[P]>
    : Prisma.GetScalarType<T[P], AggregateServiceFeature[P]>
}




export type ServiceFeatureGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ServiceFeatureWhereInput
  orderBy?: Prisma.ServiceFeatureOrderByWithAggregationInput | Prisma.ServiceFeatureOrderByWithAggregationInput[]
  by: Prisma.ServiceFeatureScalarFieldEnum[] | Prisma.ServiceFeatureScalarFieldEnum
  having?: Prisma.ServiceFeatureScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: ServiceFeatureCountAggregateInputType | true
  _avg?: ServiceFeatureAvgAggregateInputType
  _sum?: ServiceFeatureSumAggregateInputType
  _min?: ServiceFeatureMinAggregateInputType
  _max?: ServiceFeatureMaxAggregateInputType
}

export type ServiceFeatureGroupByOutputType = {
  id: number
  name: string
  createdAt: Date
  deletedAt: Date | null
  _count: ServiceFeatureCountAggregateOutputType | null
  _avg: ServiceFeatureAvgAggregateOutputType | null
  _sum: ServiceFeatureSumAggregateOutputType | null
  _min: ServiceFeatureMinAggregateOutputType | null
  _max: ServiceFeatureMaxAggregateOutputType | null
}

type GetServiceFeatureGroupByPayload<T extends ServiceFeatureGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<ServiceFeatureGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof ServiceFeatureGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], ServiceFeatureGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], ServiceFeatureGroupByOutputType[P]>
      }
    >
  >



export type ServiceFeatureWhereInput = {
  AND?: Prisma.ServiceFeatureWhereInput | Prisma.ServiceFeatureWhereInput[]
  OR?: Prisma.ServiceFeatureWhereInput[]
  NOT?: Prisma.ServiceFeatureWhereInput | Prisma.ServiceFeatureWhereInput[]
  id?: Prisma.IntFilter<"ServiceFeature"> | number
  name?: Prisma.StringFilter<"ServiceFeature"> | string
  createdAt?: Prisma.DateTimeFilter<"ServiceFeature"> | Date | string
  deletedAt?: Prisma.DateTimeNullableFilter<"ServiceFeature"> | Date | string | null
  featureMaps?: Prisma.ServiceFeatureMapListRelationFilter
}

export type ServiceFeatureOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  deletedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  featureMaps?: Prisma.ServiceFeatureMapOrderByRelationAggregateInput
  _relevance?: Prisma.ServiceFeatureOrderByRelevanceInput
}

export type ServiceFeatureWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  AND?: Prisma.ServiceFeatureWhereInput | Prisma.ServiceFeatureWhereInput[]
  OR?: Prisma.ServiceFeatureWhereInput[]
  NOT?: Prisma.ServiceFeatureWhereInput | Prisma.ServiceFeatureWhereInput[]
  name?: Prisma.StringFilter<"ServiceFeature"> | string
  createdAt?: Prisma.DateTimeFilter<"ServiceFeature"> | Date | string
  deletedAt?: Prisma.DateTimeNullableFilter<"ServiceFeature"> | Date | string | null
  featureMaps?: Prisma.ServiceFeatureMapListRelationFilter
}, "id">

export type ServiceFeatureOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  deletedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.ServiceFeatureCountOrderByAggregateInput
  _avg?: Prisma.ServiceFeatureAvgOrderByAggregateInput
  _max?: Prisma.ServiceFeatureMaxOrderByAggregateInput
  _min?: Prisma.ServiceFeatureMinOrderByAggregateInput
  _sum?: Prisma.ServiceFeatureSumOrderByAggregateInput
}

export type ServiceFeatureScalarWhereWithAggregatesInput = {
  AND?: Prisma.ServiceFeatureScalarWhereWithAggregatesInput | Prisma.ServiceFeatureScalarWhereWithAggregatesInput[]
  OR?: Prisma.ServiceFeatureScalarWhereWithAggregatesInput[]
  NOT?: Prisma.ServiceFeatureScalarWhereWithAggregatesInput | Prisma.ServiceFeatureScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"ServiceFeature"> | number
  name?: Prisma.StringWithAggregatesFilter<"ServiceFeature"> | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"ServiceFeature"> | Date | string
  deletedAt?: Prisma.DateTimeNullableWithAggregatesFilter<"ServiceFeature"> | Date | string | null
}

export type ServiceFeatureCreateInput = {
  name: string
  createdAt?: Date | string
  deletedAt?: Date | string | null
  featureMaps?: Prisma.ServiceFeatureMapCreateNestedManyWithoutFeatureInput
}

export type ServiceFeatureUncheckedCreateInput = {
  id?: number
  name: string
  createdAt?: Date | string
  deletedAt?: Date | string | null
  featureMaps?: Prisma.ServiceFeatureMapUncheckedCreateNestedManyWithoutFeatureInput
}

export type ServiceFeatureUpdateInput = {
  name?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  featureMaps?: Prisma.ServiceFeatureMapUpdateManyWithoutFeatureNestedInput
}

export type ServiceFeatureUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  featureMaps?: Prisma.ServiceFeatureMapUncheckedUpdateManyWithoutFeatureNestedInput
}

export type ServiceFeatureCreateManyInput = {
  id?: number
  name: string
  createdAt?: Date | string
  deletedAt?: Date | string | null
}

export type ServiceFeatureUpdateManyMutationInput = {
  name?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type ServiceFeatureUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type ServiceFeatureOrderByRelevanceInput = {
  fields: Prisma.ServiceFeatureOrderByRelevanceFieldEnum | Prisma.ServiceFeatureOrderByRelevanceFieldEnum[]
  sort: Prisma.SortOrder
  search: string
}

export type ServiceFeatureCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  deletedAt?: Prisma.SortOrder
}

export type ServiceFeatureAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
}

export type ServiceFeatureMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  deletedAt?: Prisma.SortOrder
}

export type ServiceFeatureMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  deletedAt?: Prisma.SortOrder
}

export type ServiceFeatureSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
}

export type ServiceFeatureScalarRelationFilter = {
  is?: Prisma.ServiceFeatureWhereInput
  isNot?: Prisma.ServiceFeatureWhereInput
}

export type ServiceFeatureCreateNestedOneWithoutFeatureMapsInput = {
  create?: Prisma.XOR<Prisma.ServiceFeatureCreateWithoutFeatureMapsInput, Prisma.ServiceFeatureUncheckedCreateWithoutFeatureMapsInput>
  connectOrCreate?: Prisma.ServiceFeatureCreateOrConnectWithoutFeatureMapsInput
  connect?: Prisma.ServiceFeatureWhereUniqueInput
}

export type ServiceFeatureUpdateOneRequiredWithoutFeatureMapsNestedInput = {
  create?: Prisma.XOR<Prisma.ServiceFeatureCreateWithoutFeatureMapsInput, Prisma.ServiceFeatureUncheckedCreateWithoutFeatureMapsInput>
  connectOrCreate?: Prisma.ServiceFeatureCreateOrConnectWithoutFeatureMapsInput
  upsert?: Prisma.ServiceFeatureUpsertWithoutFeatureMapsInput
  connect?: Prisma.ServiceFeatureWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.ServiceFeatureUpdateToOneWithWhereWithoutFeatureMapsInput, Prisma.ServiceFeatureUpdateWithoutFeatureMapsInput>, Prisma.ServiceFeatureUncheckedUpdateWithoutFeatureMapsInput>
}

export type ServiceFeatureCreateWithoutFeatureMapsInput = {
  name: string
  createdAt?: Date | string
  deletedAt?: Date | string | null
}

export type ServiceFeatureUncheckedCreateWithoutFeatureMapsInput = {
  id?: number
  name: string
  createdAt?: Date | string
  deletedAt?: Date | string | null
}

export type ServiceFeatureCreateOrConnectWithoutFeatureMapsInput = {
  where: Prisma.ServiceFeatureWhereUniqueInput
  create: Prisma.XOR<Prisma.ServiceFeatureCreateWithoutFeatureMapsInput, Prisma.ServiceFeatureUncheckedCreateWithoutFeatureMapsInput>
}

export type ServiceFeatureUpsertWithoutFeatureMapsInput = {
  update: Prisma.XOR<Prisma.ServiceFeatureUpdateWithoutFeatureMapsInput, Prisma.ServiceFeatureUncheckedUpdateWithoutFeatureMapsInput>
  create: Prisma.XOR<Prisma.ServiceFeatureCreateWithoutFeatureMapsInput, Prisma.ServiceFeatureUncheckedCreateWithoutFeatureMapsInput>
  where?: Prisma.ServiceFeatureWhereInput
}

export type ServiceFeatureUpdateToOneWithWhereWithoutFeatureMapsInput = {
  where?: Prisma.ServiceFeatureWhereInput
  data: Prisma.XOR<Prisma.ServiceFeatureUpdateWithoutFeatureMapsInput, Prisma.ServiceFeatureUncheckedUpdateWithoutFeatureMapsInput>
}

export type ServiceFeatureUpdateWithoutFeatureMapsInput = {
  name?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type ServiceFeatureUncheckedUpdateWithoutFeatureMapsInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}


/**
 * Count Type ServiceFeatureCountOutputType
 */

export type ServiceFeatureCountOutputType = {
  featureMaps: number
}

export type ServiceFeatureCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  featureMaps?: boolean | ServiceFeatureCountOutputTypeCountFeatureMapsArgs
}

/**
 * ServiceFeatureCountOutputType without action
 */
export type ServiceFeatureCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ServiceFeatureCountOutputType
   */
  select?: Prisma.ServiceFeatureCountOutputTypeSelect<ExtArgs> | null
}

/**
 * ServiceFeatureCountOutputType without action
 */
export type ServiceFeatureCountOutputTypeCountFeatureMapsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ServiceFeatureMapWhereInput
}


export type ServiceFeatureSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  createdAt?: boolean
  deletedAt?: boolean
  featureMaps?: boolean | Prisma.ServiceFeature$featureMapsArgs<ExtArgs>
  _count?: boolean | Prisma.ServiceFeatureCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["serviceFeature"]>



export type ServiceFeatureSelectScalar = {
  id?: boolean
  name?: boolean
  createdAt?: boolean
  deletedAt?: boolean
}

export type ServiceFeatureOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "name" | "createdAt" | "deletedAt", ExtArgs["result"]["serviceFeature"]>
export type ServiceFeatureInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  featureMaps?: boolean | Prisma.ServiceFeature$featureMapsArgs<ExtArgs>
  _count?: boolean | Prisma.ServiceFeatureCountOutputTypeDefaultArgs<ExtArgs>
}

export type $ServiceFeaturePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "ServiceFeature"
  objects: {
    featureMaps: Prisma.$ServiceFeatureMapPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    name: string
    createdAt: Date
    deletedAt: Date | null
  }, ExtArgs["result"]["serviceFeature"]>
  composites: {}
}

export type ServiceFeatureGetPayload<S extends boolean | null | undefined | ServiceFeatureDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$ServiceFeaturePayload, S>

export type ServiceFeatureCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<ServiceFeatureFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: ServiceFeatureCountAggregateInputType | true
  }

export interface ServiceFeatureDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['ServiceFeature'], meta: { name: 'ServiceFeature' } }
  /**
   * Find zero or one ServiceFeature that matches the filter.
   * @param {ServiceFeatureFindUniqueArgs} args - Arguments to find a ServiceFeature
   * @example
   * // Get one ServiceFeature
   * const serviceFeature = await prisma.serviceFeature.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends ServiceFeatureFindUniqueArgs>(args: Prisma.SelectSubset<T, ServiceFeatureFindUniqueArgs<ExtArgs>>): Prisma.Prisma__ServiceFeatureClient<runtime.Types.Result.GetResult<Prisma.$ServiceFeaturePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one ServiceFeature that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {ServiceFeatureFindUniqueOrThrowArgs} args - Arguments to find a ServiceFeature
   * @example
   * // Get one ServiceFeature
   * const serviceFeature = await prisma.serviceFeature.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends ServiceFeatureFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, ServiceFeatureFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__ServiceFeatureClient<runtime.Types.Result.GetResult<Prisma.$ServiceFeaturePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ServiceFeature that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ServiceFeatureFindFirstArgs} args - Arguments to find a ServiceFeature
   * @example
   * // Get one ServiceFeature
   * const serviceFeature = await prisma.serviceFeature.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends ServiceFeatureFindFirstArgs>(args?: Prisma.SelectSubset<T, ServiceFeatureFindFirstArgs<ExtArgs>>): Prisma.Prisma__ServiceFeatureClient<runtime.Types.Result.GetResult<Prisma.$ServiceFeaturePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ServiceFeature that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ServiceFeatureFindFirstOrThrowArgs} args - Arguments to find a ServiceFeature
   * @example
   * // Get one ServiceFeature
   * const serviceFeature = await prisma.serviceFeature.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends ServiceFeatureFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, ServiceFeatureFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__ServiceFeatureClient<runtime.Types.Result.GetResult<Prisma.$ServiceFeaturePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more ServiceFeatures that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ServiceFeatureFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all ServiceFeatures
   * const serviceFeatures = await prisma.serviceFeature.findMany()
   * 
   * // Get first 10 ServiceFeatures
   * const serviceFeatures = await prisma.serviceFeature.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const serviceFeatureWithIdOnly = await prisma.serviceFeature.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends ServiceFeatureFindManyArgs>(args?: Prisma.SelectSubset<T, ServiceFeatureFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ServiceFeaturePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a ServiceFeature.
   * @param {ServiceFeatureCreateArgs} args - Arguments to create a ServiceFeature.
   * @example
   * // Create one ServiceFeature
   * const ServiceFeature = await prisma.serviceFeature.create({
   *   data: {
   *     // ... data to create a ServiceFeature
   *   }
   * })
   * 
   */
  create<T extends ServiceFeatureCreateArgs>(args: Prisma.SelectSubset<T, ServiceFeatureCreateArgs<ExtArgs>>): Prisma.Prisma__ServiceFeatureClient<runtime.Types.Result.GetResult<Prisma.$ServiceFeaturePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many ServiceFeatures.
   * @param {ServiceFeatureCreateManyArgs} args - Arguments to create many ServiceFeatures.
   * @example
   * // Create many ServiceFeatures
   * const serviceFeature = await prisma.serviceFeature.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends ServiceFeatureCreateManyArgs>(args?: Prisma.SelectSubset<T, ServiceFeatureCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Delete a ServiceFeature.
   * @param {ServiceFeatureDeleteArgs} args - Arguments to delete one ServiceFeature.
   * @example
   * // Delete one ServiceFeature
   * const ServiceFeature = await prisma.serviceFeature.delete({
   *   where: {
   *     // ... filter to delete one ServiceFeature
   *   }
   * })
   * 
   */
  delete<T extends ServiceFeatureDeleteArgs>(args: Prisma.SelectSubset<T, ServiceFeatureDeleteArgs<ExtArgs>>): Prisma.Prisma__ServiceFeatureClient<runtime.Types.Result.GetResult<Prisma.$ServiceFeaturePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one ServiceFeature.
   * @param {ServiceFeatureUpdateArgs} args - Arguments to update one ServiceFeature.
   * @example
   * // Update one ServiceFeature
   * const serviceFeature = await prisma.serviceFeature.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends ServiceFeatureUpdateArgs>(args: Prisma.SelectSubset<T, ServiceFeatureUpdateArgs<ExtArgs>>): Prisma.Prisma__ServiceFeatureClient<runtime.Types.Result.GetResult<Prisma.$ServiceFeaturePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more ServiceFeatures.
   * @param {ServiceFeatureDeleteManyArgs} args - Arguments to filter ServiceFeatures to delete.
   * @example
   * // Delete a few ServiceFeatures
   * const { count } = await prisma.serviceFeature.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends ServiceFeatureDeleteManyArgs>(args?: Prisma.SelectSubset<T, ServiceFeatureDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ServiceFeatures.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ServiceFeatureUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many ServiceFeatures
   * const serviceFeature = await prisma.serviceFeature.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends ServiceFeatureUpdateManyArgs>(args: Prisma.SelectSubset<T, ServiceFeatureUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create or update one ServiceFeature.
   * @param {ServiceFeatureUpsertArgs} args - Arguments to update or create a ServiceFeature.
   * @example
   * // Update or create a ServiceFeature
   * const serviceFeature = await prisma.serviceFeature.upsert({
   *   create: {
   *     // ... data to create a ServiceFeature
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the ServiceFeature we want to update
   *   }
   * })
   */
  upsert<T extends ServiceFeatureUpsertArgs>(args: Prisma.SelectSubset<T, ServiceFeatureUpsertArgs<ExtArgs>>): Prisma.Prisma__ServiceFeatureClient<runtime.Types.Result.GetResult<Prisma.$ServiceFeaturePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of ServiceFeatures.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ServiceFeatureCountArgs} args - Arguments to filter ServiceFeatures to count.
   * @example
   * // Count the number of ServiceFeatures
   * const count = await prisma.serviceFeature.count({
   *   where: {
   *     // ... the filter for the ServiceFeatures we want to count
   *   }
   * })
  **/
  count<T extends ServiceFeatureCountArgs>(
    args?: Prisma.Subset<T, ServiceFeatureCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], ServiceFeatureCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a ServiceFeature.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ServiceFeatureAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends ServiceFeatureAggregateArgs>(args: Prisma.Subset<T, ServiceFeatureAggregateArgs>): Prisma.PrismaPromise<GetServiceFeatureAggregateType<T>>

  /**
   * Group by ServiceFeature.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ServiceFeatureGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends ServiceFeatureGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: ServiceFeatureGroupByArgs['orderBy'] }
      : { orderBy?: ServiceFeatureGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, ServiceFeatureGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetServiceFeatureGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the ServiceFeature model
 */
readonly fields: ServiceFeatureFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for ServiceFeature.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__ServiceFeatureClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  featureMaps<T extends Prisma.ServiceFeature$featureMapsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ServiceFeature$featureMapsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ServiceFeatureMapPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the ServiceFeature model
 */
export interface ServiceFeatureFieldRefs {
  readonly id: Prisma.FieldRef<"ServiceFeature", 'Int'>
  readonly name: Prisma.FieldRef<"ServiceFeature", 'String'>
  readonly createdAt: Prisma.FieldRef<"ServiceFeature", 'DateTime'>
  readonly deletedAt: Prisma.FieldRef<"ServiceFeature", 'DateTime'>
}
    

// Custom InputTypes
/**
 * ServiceFeature findUnique
 */
export type ServiceFeatureFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ServiceFeature
   */
  select?: Prisma.ServiceFeatureSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ServiceFeature
   */
  omit?: Prisma.ServiceFeatureOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ServiceFeatureInclude<ExtArgs> | null
  /**
   * Filter, which ServiceFeature to fetch.
   */
  where: Prisma.ServiceFeatureWhereUniqueInput
}

/**
 * ServiceFeature findUniqueOrThrow
 */
export type ServiceFeatureFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ServiceFeature
   */
  select?: Prisma.ServiceFeatureSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ServiceFeature
   */
  omit?: Prisma.ServiceFeatureOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ServiceFeatureInclude<ExtArgs> | null
  /**
   * Filter, which ServiceFeature to fetch.
   */
  where: Prisma.ServiceFeatureWhereUniqueInput
}

/**
 * ServiceFeature findFirst
 */
export type ServiceFeatureFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ServiceFeature
   */
  select?: Prisma.ServiceFeatureSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ServiceFeature
   */
  omit?: Prisma.ServiceFeatureOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ServiceFeatureInclude<ExtArgs> | null
  /**
   * Filter, which ServiceFeature to fetch.
   */
  where?: Prisma.ServiceFeatureWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ServiceFeatures to fetch.
   */
  orderBy?: Prisma.ServiceFeatureOrderByWithRelationInput | Prisma.ServiceFeatureOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ServiceFeatures.
   */
  cursor?: Prisma.ServiceFeatureWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ServiceFeatures from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ServiceFeatures.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ServiceFeatures.
   */
  distinct?: Prisma.ServiceFeatureScalarFieldEnum | Prisma.ServiceFeatureScalarFieldEnum[]
}

/**
 * ServiceFeature findFirstOrThrow
 */
export type ServiceFeatureFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ServiceFeature
   */
  select?: Prisma.ServiceFeatureSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ServiceFeature
   */
  omit?: Prisma.ServiceFeatureOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ServiceFeatureInclude<ExtArgs> | null
  /**
   * Filter, which ServiceFeature to fetch.
   */
  where?: Prisma.ServiceFeatureWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ServiceFeatures to fetch.
   */
  orderBy?: Prisma.ServiceFeatureOrderByWithRelationInput | Prisma.ServiceFeatureOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ServiceFeatures.
   */
  cursor?: Prisma.ServiceFeatureWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ServiceFeatures from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ServiceFeatures.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ServiceFeatures.
   */
  distinct?: Prisma.ServiceFeatureScalarFieldEnum | Prisma.ServiceFeatureScalarFieldEnum[]
}

/**
 * ServiceFeature findMany
 */
export type ServiceFeatureFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ServiceFeature
   */
  select?: Prisma.ServiceFeatureSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ServiceFeature
   */
  omit?: Prisma.ServiceFeatureOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ServiceFeatureInclude<ExtArgs> | null
  /**
   * Filter, which ServiceFeatures to fetch.
   */
  where?: Prisma.ServiceFeatureWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ServiceFeatures to fetch.
   */
  orderBy?: Prisma.ServiceFeatureOrderByWithRelationInput | Prisma.ServiceFeatureOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing ServiceFeatures.
   */
  cursor?: Prisma.ServiceFeatureWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ServiceFeatures from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ServiceFeatures.
   */
  skip?: number
  distinct?: Prisma.ServiceFeatureScalarFieldEnum | Prisma.ServiceFeatureScalarFieldEnum[]
}

/**
 * ServiceFeature create
 */
export type ServiceFeatureCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ServiceFeature
   */
  select?: Prisma.ServiceFeatureSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ServiceFeature
   */
  omit?: Prisma.ServiceFeatureOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ServiceFeatureInclude<ExtArgs> | null
  /**
   * The data needed to create a ServiceFeature.
   */
  data: Prisma.XOR<Prisma.ServiceFeatureCreateInput, Prisma.ServiceFeatureUncheckedCreateInput>
}

/**
 * ServiceFeature createMany
 */
export type ServiceFeatureCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many ServiceFeatures.
   */
  data: Prisma.ServiceFeatureCreateManyInput | Prisma.ServiceFeatureCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * ServiceFeature update
 */
export type ServiceFeatureUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ServiceFeature
   */
  select?: Prisma.ServiceFeatureSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ServiceFeature
   */
  omit?: Prisma.ServiceFeatureOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ServiceFeatureInclude<ExtArgs> | null
  /**
   * The data needed to update a ServiceFeature.
   */
  data: Prisma.XOR<Prisma.ServiceFeatureUpdateInput, Prisma.ServiceFeatureUncheckedUpdateInput>
  /**
   * Choose, which ServiceFeature to update.
   */
  where: Prisma.ServiceFeatureWhereUniqueInput
}

/**
 * ServiceFeature updateMany
 */
export type ServiceFeatureUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update ServiceFeatures.
   */
  data: Prisma.XOR<Prisma.ServiceFeatureUpdateManyMutationInput, Prisma.ServiceFeatureUncheckedUpdateManyInput>
  /**
   * Filter which ServiceFeatures to update
   */
  where?: Prisma.ServiceFeatureWhereInput
  /**
   * Limit how many ServiceFeatures to update.
   */
  limit?: number
}

/**
 * ServiceFeature upsert
 */
export type ServiceFeatureUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ServiceFeature
   */
  select?: Prisma.ServiceFeatureSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ServiceFeature
   */
  omit?: Prisma.ServiceFeatureOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ServiceFeatureInclude<ExtArgs> | null
  /**
   * The filter to search for the ServiceFeature to update in case it exists.
   */
  where: Prisma.ServiceFeatureWhereUniqueInput
  /**
   * In case the ServiceFeature found by the `where` argument doesn't exist, create a new ServiceFeature with this data.
   */
  create: Prisma.XOR<Prisma.ServiceFeatureCreateInput, Prisma.ServiceFeatureUncheckedCreateInput>
  /**
   * In case the ServiceFeature was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.ServiceFeatureUpdateInput, Prisma.ServiceFeatureUncheckedUpdateInput>
}

/**
 * ServiceFeature delete
 */
export type ServiceFeatureDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ServiceFeature
   */
  select?: Prisma.ServiceFeatureSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ServiceFeature
   */
  omit?: Prisma.ServiceFeatureOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ServiceFeatureInclude<ExtArgs> | null
  /**
   * Filter which ServiceFeature to delete.
   */
  where: Prisma.ServiceFeatureWhereUniqueInput
}

/**
 * ServiceFeature deleteMany
 */
export type ServiceFeatureDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ServiceFeatures to delete
   */
  where?: Prisma.ServiceFeatureWhereInput
  /**
   * Limit how many ServiceFeatures to delete.
   */
  limit?: number
}

/**
 * ServiceFeature.featureMaps
 */
export type ServiceFeature$featureMapsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ServiceFeatureMap
   */
  select?: Prisma.ServiceFeatureMapSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ServiceFeatureMap
   */
  omit?: Prisma.ServiceFeatureMapOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ServiceFeatureMapInclude<ExtArgs> | null
  where?: Prisma.ServiceFeatureMapWhereInput
  orderBy?: Prisma.ServiceFeatureMapOrderByWithRelationInput | Prisma.ServiceFeatureMapOrderByWithRelationInput[]
  cursor?: Prisma.ServiceFeatureMapWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.ServiceFeatureMapScalarFieldEnum | Prisma.ServiceFeatureMapScalarFieldEnum[]
}

/**
 * ServiceFeature without action
 */
export type ServiceFeatureDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ServiceFeature
   */
  select?: Prisma.ServiceFeatureSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ServiceFeature
   */
  omit?: Prisma.ServiceFeatureOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ServiceFeatureInclude<ExtArgs> | null
}
