
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `ServiceFeatureMap` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model ServiceFeatureMap
 * 
 */
export type ServiceFeatureMapModel = runtime.Types.Result.DefaultSelection<Prisma.$ServiceFeatureMapPayload>

export type AggregateServiceFeatureMap = {
  _count: ServiceFeatureMapCountAggregateOutputType | null
  _avg: ServiceFeatureMapAvgAggregateOutputType | null
  _sum: ServiceFeatureMapSumAggregateOutputType | null
  _min: ServiceFeatureMapMinAggregateOutputType | null
  _max: ServiceFeatureMapMaxAggregateOutputType | null
}

export type ServiceFeatureMapAvgAggregateOutputType = {
  id: number | null
  serviceId: number | null
  featureId: number | null
}

export type ServiceFeatureMapSumAggregateOutputType = {
  id: bigint | null
  serviceId: bigint | null
  featureId: bigint | null
}

export type ServiceFeatureMapMinAggregateOutputType = {
  id: bigint | null
  serviceId: bigint | null
  featureId: bigint | null
}

export type ServiceFeatureMapMaxAggregateOutputType = {
  id: bigint | null
  serviceId: bigint | null
  featureId: bigint | null
}

export type ServiceFeatureMapCountAggregateOutputType = {
  id: number
  serviceId: number
  featureId: number
  _all: number
}


export type ServiceFeatureMapAvgAggregateInputType = {
  id?: true
  serviceId?: true
  featureId?: true
}

export type ServiceFeatureMapSumAggregateInputType = {
  id?: true
  serviceId?: true
  featureId?: true
}

export type ServiceFeatureMapMinAggregateInputType = {
  id?: true
  serviceId?: true
  featureId?: true
}

export type ServiceFeatureMapMaxAggregateInputType = {
  id?: true
  serviceId?: true
  featureId?: true
}

export type ServiceFeatureMapCountAggregateInputType = {
  id?: true
  serviceId?: true
  featureId?: true
  _all?: true
}

export type ServiceFeatureMapAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ServiceFeatureMap to aggregate.
   */
  where?: Prisma.ServiceFeatureMapWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ServiceFeatureMaps to fetch.
   */
  orderBy?: Prisma.ServiceFeatureMapOrderByWithRelationInput | Prisma.ServiceFeatureMapOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.ServiceFeatureMapWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ServiceFeatureMaps from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ServiceFeatureMaps.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned ServiceFeatureMaps
  **/
  _count?: true | ServiceFeatureMapCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: ServiceFeatureMapAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: ServiceFeatureMapSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: ServiceFeatureMapMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: ServiceFeatureMapMaxAggregateInputType
}

export type GetServiceFeatureMapAggregateType<T extends ServiceFeatureMapAggregateArgs> = {
      [P in keyof T & keyof AggregateServiceFeatureMap]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateServiceFeatureMap[P]>
    : Prisma.GetScalarType<T[P], AggregateServiceFeatureMap[P]>
}




export type ServiceFeatureMapGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ServiceFeatureMapWhereInput
  orderBy?: Prisma.ServiceFeatureMapOrderByWithAggregationInput | Prisma.ServiceFeatureMapOrderByWithAggregationInput[]
  by: Prisma.ServiceFeatureMapScalarFieldEnum[] | Prisma.ServiceFeatureMapScalarFieldEnum
  having?: Prisma.ServiceFeatureMapScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: ServiceFeatureMapCountAggregateInputType | true
  _avg?: ServiceFeatureMapAvgAggregateInputType
  _sum?: ServiceFeatureMapSumAggregateInputType
  _min?: ServiceFeatureMapMinAggregateInputType
  _max?: ServiceFeatureMapMaxAggregateInputType
}

export type ServiceFeatureMapGroupByOutputType = {
  id: bigint
  serviceId: bigint
  featureId: bigint
  _count: ServiceFeatureMapCountAggregateOutputType | null
  _avg: ServiceFeatureMapAvgAggregateOutputType | null
  _sum: ServiceFeatureMapSumAggregateOutputType | null
  _min: ServiceFeatureMapMinAggregateOutputType | null
  _max: ServiceFeatureMapMaxAggregateOutputType | null
}

type GetServiceFeatureMapGroupByPayload<T extends ServiceFeatureMapGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<ServiceFeatureMapGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof ServiceFeatureMapGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], ServiceFeatureMapGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], ServiceFeatureMapGroupByOutputType[P]>
      }
    >
  >



export type ServiceFeatureMapWhereInput = {
  AND?: Prisma.ServiceFeatureMapWhereInput | Prisma.ServiceFeatureMapWhereInput[]
  OR?: Prisma.ServiceFeatureMapWhereInput[]
  NOT?: Prisma.ServiceFeatureMapWhereInput | Prisma.ServiceFeatureMapWhereInput[]
  id?: Prisma.BigIntFilter<"ServiceFeatureMap"> | bigint | number
  serviceId?: Prisma.BigIntFilter<"ServiceFeatureMap"> | bigint | number
  featureId?: Prisma.BigIntFilter<"ServiceFeatureMap"> | bigint | number
  service?: Prisma.XOR<Prisma.ServiceScalarRelationFilter, Prisma.ServiceWhereInput>
  feature?: Prisma.XOR<Prisma.ServiceFeatureScalarRelationFilter, Prisma.ServiceFeatureWhereInput>
}

export type ServiceFeatureMapOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  serviceId?: Prisma.SortOrder
  featureId?: Prisma.SortOrder
  service?: Prisma.ServiceOrderByWithRelationInput
  feature?: Prisma.ServiceFeatureOrderByWithRelationInput
}

export type ServiceFeatureMapWhereUniqueInput = Prisma.AtLeast<{
  id?: bigint | number
  serviceId_featureId?: Prisma.ServiceFeatureMapServiceIdFeatureIdCompoundUniqueInput
  AND?: Prisma.ServiceFeatureMapWhereInput | Prisma.ServiceFeatureMapWhereInput[]
  OR?: Prisma.ServiceFeatureMapWhereInput[]
  NOT?: Prisma.ServiceFeatureMapWhereInput | Prisma.ServiceFeatureMapWhereInput[]
  serviceId?: Prisma.BigIntFilter<"ServiceFeatureMap"> | bigint | number
  featureId?: Prisma.BigIntFilter<"ServiceFeatureMap"> | bigint | number
  service?: Prisma.XOR<Prisma.ServiceScalarRelationFilter, Prisma.ServiceWhereInput>
  feature?: Prisma.XOR<Prisma.ServiceFeatureScalarRelationFilter, Prisma.ServiceFeatureWhereInput>
}, "id" | "serviceId_featureId">

export type ServiceFeatureMapOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  serviceId?: Prisma.SortOrder
  featureId?: Prisma.SortOrder
  _count?: Prisma.ServiceFeatureMapCountOrderByAggregateInput
  _avg?: Prisma.ServiceFeatureMapAvgOrderByAggregateInput
  _max?: Prisma.ServiceFeatureMapMaxOrderByAggregateInput
  _min?: Prisma.ServiceFeatureMapMinOrderByAggregateInput
  _sum?: Prisma.ServiceFeatureMapSumOrderByAggregateInput
}

export type ServiceFeatureMapScalarWhereWithAggregatesInput = {
  AND?: Prisma.ServiceFeatureMapScalarWhereWithAggregatesInput | Prisma.ServiceFeatureMapScalarWhereWithAggregatesInput[]
  OR?: Prisma.ServiceFeatureMapScalarWhereWithAggregatesInput[]
  NOT?: Prisma.ServiceFeatureMapScalarWhereWithAggregatesInput | Prisma.ServiceFeatureMapScalarWhereWithAggregatesInput[]
  id?: Prisma.BigIntWithAggregatesFilter<"ServiceFeatureMap"> | bigint | number
  serviceId?: Prisma.BigIntWithAggregatesFilter<"ServiceFeatureMap"> | bigint | number
  featureId?: Prisma.BigIntWithAggregatesFilter<"ServiceFeatureMap"> | bigint | number
}

export type ServiceFeatureMapCreateInput = {
  id?: bigint | number
  service: Prisma.ServiceCreateNestedOneWithoutFeatureMapsInput
  feature: Prisma.ServiceFeatureCreateNestedOneWithoutFeatureMapsInput
}

export type ServiceFeatureMapUncheckedCreateInput = {
  id?: bigint | number
  serviceId: bigint | number
  featureId: bigint | number
}

export type ServiceFeatureMapUpdateInput = {
  id?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  service?: Prisma.ServiceUpdateOneRequiredWithoutFeatureMapsNestedInput
  feature?: Prisma.ServiceFeatureUpdateOneRequiredWithoutFeatureMapsNestedInput
}

export type ServiceFeatureMapUncheckedUpdateInput = {
  id?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  serviceId?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  featureId?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
}

export type ServiceFeatureMapCreateManyInput = {
  id?: bigint | number
  serviceId: bigint | number
  featureId: bigint | number
}

export type ServiceFeatureMapUpdateManyMutationInput = {
  id?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
}

export type ServiceFeatureMapUncheckedUpdateManyInput = {
  id?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  serviceId?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  featureId?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
}

export type ServiceFeatureMapListRelationFilter = {
  every?: Prisma.ServiceFeatureMapWhereInput
  some?: Prisma.ServiceFeatureMapWhereInput
  none?: Prisma.ServiceFeatureMapWhereInput
}

export type ServiceFeatureMapOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type ServiceFeatureMapServiceIdFeatureIdCompoundUniqueInput = {
  serviceId: bigint | number
  featureId: bigint | number
}

export type ServiceFeatureMapCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  serviceId?: Prisma.SortOrder
  featureId?: Prisma.SortOrder
}

export type ServiceFeatureMapAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
  serviceId?: Prisma.SortOrder
  featureId?: Prisma.SortOrder
}

export type ServiceFeatureMapMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  serviceId?: Prisma.SortOrder
  featureId?: Prisma.SortOrder
}

export type ServiceFeatureMapMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  serviceId?: Prisma.SortOrder
  featureId?: Prisma.SortOrder
}

export type ServiceFeatureMapSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
  serviceId?: Prisma.SortOrder
  featureId?: Prisma.SortOrder
}

export type ServiceFeatureMapCreateNestedManyWithoutServiceInput = {
  create?: Prisma.XOR<Prisma.ServiceFeatureMapCreateWithoutServiceInput, Prisma.ServiceFeatureMapUncheckedCreateWithoutServiceInput> | Prisma.ServiceFeatureMapCreateWithoutServiceInput[] | Prisma.ServiceFeatureMapUncheckedCreateWithoutServiceInput[]
  connectOrCreate?: Prisma.ServiceFeatureMapCreateOrConnectWithoutServiceInput | Prisma.ServiceFeatureMapCreateOrConnectWithoutServiceInput[]
  createMany?: Prisma.ServiceFeatureMapCreateManyServiceInputEnvelope
  connect?: Prisma.ServiceFeatureMapWhereUniqueInput | Prisma.ServiceFeatureMapWhereUniqueInput[]
}

export type ServiceFeatureMapUncheckedCreateNestedManyWithoutServiceInput = {
  create?: Prisma.XOR<Prisma.ServiceFeatureMapCreateWithoutServiceInput, Prisma.ServiceFeatureMapUncheckedCreateWithoutServiceInput> | Prisma.ServiceFeatureMapCreateWithoutServiceInput[] | Prisma.ServiceFeatureMapUncheckedCreateWithoutServiceInput[]
  connectOrCreate?: Prisma.ServiceFeatureMapCreateOrConnectWithoutServiceInput | Prisma.ServiceFeatureMapCreateOrConnectWithoutServiceInput[]
  createMany?: Prisma.ServiceFeatureMapCreateManyServiceInputEnvelope
  connect?: Prisma.ServiceFeatureMapWhereUniqueInput | Prisma.ServiceFeatureMapWhereUniqueInput[]
}

export type ServiceFeatureMapUpdateManyWithoutServiceNestedInput = {
  create?: Prisma.XOR<Prisma.ServiceFeatureMapCreateWithoutServiceInput, Prisma.ServiceFeatureMapUncheckedCreateWithoutServiceInput> | Prisma.ServiceFeatureMapCreateWithoutServiceInput[] | Prisma.ServiceFeatureMapUncheckedCreateWithoutServiceInput[]
  connectOrCreate?: Prisma.ServiceFeatureMapCreateOrConnectWithoutServiceInput | Prisma.ServiceFeatureMapCreateOrConnectWithoutServiceInput[]
  upsert?: Prisma.ServiceFeatureMapUpsertWithWhereUniqueWithoutServiceInput | Prisma.ServiceFeatureMapUpsertWithWhereUniqueWithoutServiceInput[]
  createMany?: Prisma.ServiceFeatureMapCreateManyServiceInputEnvelope
  set?: Prisma.ServiceFeatureMapWhereUniqueInput | Prisma.ServiceFeatureMapWhereUniqueInput[]
  disconnect?: Prisma.ServiceFeatureMapWhereUniqueInput | Prisma.ServiceFeatureMapWhereUniqueInput[]
  delete?: Prisma.ServiceFeatureMapWhereUniqueInput | Prisma.ServiceFeatureMapWhereUniqueInput[]
  connect?: Prisma.ServiceFeatureMapWhereUniqueInput | Prisma.ServiceFeatureMapWhereUniqueInput[]
  update?: Prisma.ServiceFeatureMapUpdateWithWhereUniqueWithoutServiceInput | Prisma.ServiceFeatureMapUpdateWithWhereUniqueWithoutServiceInput[]
  updateMany?: Prisma.ServiceFeatureMapUpdateManyWithWhereWithoutServiceInput | Prisma.ServiceFeatureMapUpdateManyWithWhereWithoutServiceInput[]
  deleteMany?: Prisma.ServiceFeatureMapScalarWhereInput | Prisma.ServiceFeatureMapScalarWhereInput[]
}

export type ServiceFeatureMapUncheckedUpdateManyWithoutServiceNestedInput = {
  create?: Prisma.XOR<Prisma.ServiceFeatureMapCreateWithoutServiceInput, Prisma.ServiceFeatureMapUncheckedCreateWithoutServiceInput> | Prisma.ServiceFeatureMapCreateWithoutServiceInput[] | Prisma.ServiceFeatureMapUncheckedCreateWithoutServiceInput[]
  connectOrCreate?: Prisma.ServiceFeatureMapCreateOrConnectWithoutServiceInput | Prisma.ServiceFeatureMapCreateOrConnectWithoutServiceInput[]
  upsert?: Prisma.ServiceFeatureMapUpsertWithWhereUniqueWithoutServiceInput | Prisma.ServiceFeatureMapUpsertWithWhereUniqueWithoutServiceInput[]
  createMany?: Prisma.ServiceFeatureMapCreateManyServiceInputEnvelope
  set?: Prisma.ServiceFeatureMapWhereUniqueInput | Prisma.ServiceFeatureMapWhereUniqueInput[]
  disconnect?: Prisma.ServiceFeatureMapWhereUniqueInput | Prisma.ServiceFeatureMapWhereUniqueInput[]
  delete?: Prisma.ServiceFeatureMapWhereUniqueInput | Prisma.ServiceFeatureMapWhereUniqueInput[]
  connect?: Prisma.ServiceFeatureMapWhereUniqueInput | Prisma.ServiceFeatureMapWhereUniqueInput[]
  update?: Prisma.ServiceFeatureMapUpdateWithWhereUniqueWithoutServiceInput | Prisma.ServiceFeatureMapUpdateWithWhereUniqueWithoutServiceInput[]
  updateMany?: Prisma.ServiceFeatureMapUpdateManyWithWhereWithoutServiceInput | Prisma.ServiceFeatureMapUpdateManyWithWhereWithoutServiceInput[]
  deleteMany?: Prisma.ServiceFeatureMapScalarWhereInput | Prisma.ServiceFeatureMapScalarWhereInput[]
}

export type ServiceFeatureMapCreateNestedManyWithoutFeatureInput = {
  create?: Prisma.XOR<Prisma.ServiceFeatureMapCreateWithoutFeatureInput, Prisma.ServiceFeatureMapUncheckedCreateWithoutFeatureInput> | Prisma.ServiceFeatureMapCreateWithoutFeatureInput[] | Prisma.ServiceFeatureMapUncheckedCreateWithoutFeatureInput[]
  connectOrCreate?: Prisma.ServiceFeatureMapCreateOrConnectWithoutFeatureInput | Prisma.ServiceFeatureMapCreateOrConnectWithoutFeatureInput[]
  createMany?: Prisma.ServiceFeatureMapCreateManyFeatureInputEnvelope
  connect?: Prisma.ServiceFeatureMapWhereUniqueInput | Prisma.ServiceFeatureMapWhereUniqueInput[]
}

export type ServiceFeatureMapUncheckedCreateNestedManyWithoutFeatureInput = {
  create?: Prisma.XOR<Prisma.ServiceFeatureMapCreateWithoutFeatureInput, Prisma.ServiceFeatureMapUncheckedCreateWithoutFeatureInput> | Prisma.ServiceFeatureMapCreateWithoutFeatureInput[] | Prisma.ServiceFeatureMapUncheckedCreateWithoutFeatureInput[]
  connectOrCreate?: Prisma.ServiceFeatureMapCreateOrConnectWithoutFeatureInput | Prisma.ServiceFeatureMapCreateOrConnectWithoutFeatureInput[]
  createMany?: Prisma.ServiceFeatureMapCreateManyFeatureInputEnvelope
  connect?: Prisma.ServiceFeatureMapWhereUniqueInput | Prisma.ServiceFeatureMapWhereUniqueInput[]
}

export type ServiceFeatureMapUpdateManyWithoutFeatureNestedInput = {
  create?: Prisma.XOR<Prisma.ServiceFeatureMapCreateWithoutFeatureInput, Prisma.ServiceFeatureMapUncheckedCreateWithoutFeatureInput> | Prisma.ServiceFeatureMapCreateWithoutFeatureInput[] | Prisma.ServiceFeatureMapUncheckedCreateWithoutFeatureInput[]
  connectOrCreate?: Prisma.ServiceFeatureMapCreateOrConnectWithoutFeatureInput | Prisma.ServiceFeatureMapCreateOrConnectWithoutFeatureInput[]
  upsert?: Prisma.ServiceFeatureMapUpsertWithWhereUniqueWithoutFeatureInput | Prisma.ServiceFeatureMapUpsertWithWhereUniqueWithoutFeatureInput[]
  createMany?: Prisma.ServiceFeatureMapCreateManyFeatureInputEnvelope
  set?: Prisma.ServiceFeatureMapWhereUniqueInput | Prisma.ServiceFeatureMapWhereUniqueInput[]
  disconnect?: Prisma.ServiceFeatureMapWhereUniqueInput | Prisma.ServiceFeatureMapWhereUniqueInput[]
  delete?: Prisma.ServiceFeatureMapWhereUniqueInput | Prisma.ServiceFeatureMapWhereUniqueInput[]
  connect?: Prisma.ServiceFeatureMapWhereUniqueInput | Prisma.ServiceFeatureMapWhereUniqueInput[]
  update?: Prisma.ServiceFeatureMapUpdateWithWhereUniqueWithoutFeatureInput | Prisma.ServiceFeatureMapUpdateWithWhereUniqueWithoutFeatureInput[]
  updateMany?: Prisma.ServiceFeatureMapUpdateManyWithWhereWithoutFeatureInput | Prisma.ServiceFeatureMapUpdateManyWithWhereWithoutFeatureInput[]
  deleteMany?: Prisma.ServiceFeatureMapScalarWhereInput | Prisma.ServiceFeatureMapScalarWhereInput[]
}

export type ServiceFeatureMapUncheckedUpdateManyWithoutFeatureNestedInput = {
  create?: Prisma.XOR<Prisma.ServiceFeatureMapCreateWithoutFeatureInput, Prisma.ServiceFeatureMapUncheckedCreateWithoutFeatureInput> | Prisma.ServiceFeatureMapCreateWithoutFeatureInput[] | Prisma.ServiceFeatureMapUncheckedCreateWithoutFeatureInput[]
  connectOrCreate?: Prisma.ServiceFeatureMapCreateOrConnectWithoutFeatureInput | Prisma.ServiceFeatureMapCreateOrConnectWithoutFeatureInput[]
  upsert?: Prisma.ServiceFeatureMapUpsertWithWhereUniqueWithoutFeatureInput | Prisma.ServiceFeatureMapUpsertWithWhereUniqueWithoutFeatureInput[]
  createMany?: Prisma.ServiceFeatureMapCreateManyFeatureInputEnvelope
  set?: Prisma.ServiceFeatureMapWhereUniqueInput | Prisma.ServiceFeatureMapWhereUniqueInput[]
  disconnect?: Prisma.ServiceFeatureMapWhereUniqueInput | Prisma.ServiceFeatureMapWhereUniqueInput[]
  delete?: Prisma.ServiceFeatureMapWhereUniqueInput | Prisma.ServiceFeatureMapWhereUniqueInput[]
  connect?: Prisma.ServiceFeatureMapWhereUniqueInput | Prisma.ServiceFeatureMapWhereUniqueInput[]
  update?: Prisma.ServiceFeatureMapUpdateWithWhereUniqueWithoutFeatureInput | Prisma.ServiceFeatureMapUpdateWithWhereUniqueWithoutFeatureInput[]
  updateMany?: Prisma.ServiceFeatureMapUpdateManyWithWhereWithoutFeatureInput | Prisma.ServiceFeatureMapUpdateManyWithWhereWithoutFeatureInput[]
  deleteMany?: Prisma.ServiceFeatureMapScalarWhereInput | Prisma.ServiceFeatureMapScalarWhereInput[]
}

export type ServiceFeatureMapCreateWithoutServiceInput = {
  id?: bigint | number
  feature: Prisma.ServiceFeatureCreateNestedOneWithoutFeatureMapsInput
}

export type ServiceFeatureMapUncheckedCreateWithoutServiceInput = {
  id?: bigint | number
  featureId: bigint | number
}

export type ServiceFeatureMapCreateOrConnectWithoutServiceInput = {
  where: Prisma.ServiceFeatureMapWhereUniqueInput
  create: Prisma.XOR<Prisma.ServiceFeatureMapCreateWithoutServiceInput, Prisma.ServiceFeatureMapUncheckedCreateWithoutServiceInput>
}

export type ServiceFeatureMapCreateManyServiceInputEnvelope = {
  data: Prisma.ServiceFeatureMapCreateManyServiceInput | Prisma.ServiceFeatureMapCreateManyServiceInput[]
  skipDuplicates?: boolean
}

export type ServiceFeatureMapUpsertWithWhereUniqueWithoutServiceInput = {
  where: Prisma.ServiceFeatureMapWhereUniqueInput
  update: Prisma.XOR<Prisma.ServiceFeatureMapUpdateWithoutServiceInput, Prisma.ServiceFeatureMapUncheckedUpdateWithoutServiceInput>
  create: Prisma.XOR<Prisma.ServiceFeatureMapCreateWithoutServiceInput, Prisma.ServiceFeatureMapUncheckedCreateWithoutServiceInput>
}

export type ServiceFeatureMapUpdateWithWhereUniqueWithoutServiceInput = {
  where: Prisma.ServiceFeatureMapWhereUniqueInput
  data: Prisma.XOR<Prisma.ServiceFeatureMapUpdateWithoutServiceInput, Prisma.ServiceFeatureMapUncheckedUpdateWithoutServiceInput>
}

export type ServiceFeatureMapUpdateManyWithWhereWithoutServiceInput = {
  where: Prisma.ServiceFeatureMapScalarWhereInput
  data: Prisma.XOR<Prisma.ServiceFeatureMapUpdateManyMutationInput, Prisma.ServiceFeatureMapUncheckedUpdateManyWithoutServiceInput>
}

export type ServiceFeatureMapScalarWhereInput = {
  AND?: Prisma.ServiceFeatureMapScalarWhereInput | Prisma.ServiceFeatureMapScalarWhereInput[]
  OR?: Prisma.ServiceFeatureMapScalarWhereInput[]
  NOT?: Prisma.ServiceFeatureMapScalarWhereInput | Prisma.ServiceFeatureMapScalarWhereInput[]
  id?: Prisma.BigIntFilter<"ServiceFeatureMap"> | bigint | number
  serviceId?: Prisma.BigIntFilter<"ServiceFeatureMap"> | bigint | number
  featureId?: Prisma.BigIntFilter<"ServiceFeatureMap"> | bigint | number
}

export type ServiceFeatureMapCreateWithoutFeatureInput = {
  id?: bigint | number
  service: Prisma.ServiceCreateNestedOneWithoutFeatureMapsInput
}

export type ServiceFeatureMapUncheckedCreateWithoutFeatureInput = {
  id?: bigint | number
  serviceId: bigint | number
}

export type ServiceFeatureMapCreateOrConnectWithoutFeatureInput = {
  where: Prisma.ServiceFeatureMapWhereUniqueInput
  create: Prisma.XOR<Prisma.ServiceFeatureMapCreateWithoutFeatureInput, Prisma.ServiceFeatureMapUncheckedCreateWithoutFeatureInput>
}

export type ServiceFeatureMapCreateManyFeatureInputEnvelope = {
  data: Prisma.ServiceFeatureMapCreateManyFeatureInput | Prisma.ServiceFeatureMapCreateManyFeatureInput[]
  skipDuplicates?: boolean
}

export type ServiceFeatureMapUpsertWithWhereUniqueWithoutFeatureInput = {
  where: Prisma.ServiceFeatureMapWhereUniqueInput
  update: Prisma.XOR<Prisma.ServiceFeatureMapUpdateWithoutFeatureInput, Prisma.ServiceFeatureMapUncheckedUpdateWithoutFeatureInput>
  create: Prisma.XOR<Prisma.ServiceFeatureMapCreateWithoutFeatureInput, Prisma.ServiceFeatureMapUncheckedCreateWithoutFeatureInput>
}

export type ServiceFeatureMapUpdateWithWhereUniqueWithoutFeatureInput = {
  where: Prisma.ServiceFeatureMapWhereUniqueInput
  data: Prisma.XOR<Prisma.ServiceFeatureMapUpdateWithoutFeatureInput, Prisma.ServiceFeatureMapUncheckedUpdateWithoutFeatureInput>
}

export type ServiceFeatureMapUpdateManyWithWhereWithoutFeatureInput = {
  where: Prisma.ServiceFeatureMapScalarWhereInput
  data: Prisma.XOR<Prisma.ServiceFeatureMapUpdateManyMutationInput, Prisma.ServiceFeatureMapUncheckedUpdateManyWithoutFeatureInput>
}

export type ServiceFeatureMapCreateManyServiceInput = {
  id?: bigint | number
  featureId: bigint | number
}

export type ServiceFeatureMapUpdateWithoutServiceInput = {
  id?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  feature?: Prisma.ServiceFeatureUpdateOneRequiredWithoutFeatureMapsNestedInput
}

export type ServiceFeatureMapUncheckedUpdateWithoutServiceInput = {
  id?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  featureId?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
}

export type ServiceFeatureMapUncheckedUpdateManyWithoutServiceInput = {
  id?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  featureId?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
}

export type ServiceFeatureMapCreateManyFeatureInput = {
  id?: bigint | number
  serviceId: bigint | number
}

export type ServiceFeatureMapUpdateWithoutFeatureInput = {
  id?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  service?: Prisma.ServiceUpdateOneRequiredWithoutFeatureMapsNestedInput
}

export type ServiceFeatureMapUncheckedUpdateWithoutFeatureInput = {
  id?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  serviceId?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
}

export type ServiceFeatureMapUncheckedUpdateManyWithoutFeatureInput = {
  id?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  serviceId?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
}



export type ServiceFeatureMapSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  serviceId?: boolean
  featureId?: boolean
  service?: boolean | Prisma.ServiceDefaultArgs<ExtArgs>
  feature?: boolean | Prisma.ServiceFeatureDefaultArgs<ExtArgs>
}, ExtArgs["result"]["serviceFeatureMap"]>



export type ServiceFeatureMapSelectScalar = {
  id?: boolean
  serviceId?: boolean
  featureId?: boolean
}

export type ServiceFeatureMapOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "serviceId" | "featureId", ExtArgs["result"]["serviceFeatureMap"]>
export type ServiceFeatureMapInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  service?: boolean | Prisma.ServiceDefaultArgs<ExtArgs>
  feature?: boolean | Prisma.ServiceFeatureDefaultArgs<ExtArgs>
}

export type $ServiceFeatureMapPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "ServiceFeatureMap"
  objects: {
    service: Prisma.$ServicePayload<ExtArgs>
    feature: Prisma.$ServiceFeaturePayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: bigint
    serviceId: bigint
    featureId: bigint
  }, ExtArgs["result"]["serviceFeatureMap"]>
  composites: {}
}

export type ServiceFeatureMapGetPayload<S extends boolean | null | undefined | ServiceFeatureMapDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$ServiceFeatureMapPayload, S>

export type ServiceFeatureMapCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<ServiceFeatureMapFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: ServiceFeatureMapCountAggregateInputType | true
  }

export interface ServiceFeatureMapDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['ServiceFeatureMap'], meta: { name: 'ServiceFeatureMap' } }
  /**
   * Find zero or one ServiceFeatureMap that matches the filter.
   * @param {ServiceFeatureMapFindUniqueArgs} args - Arguments to find a ServiceFeatureMap
   * @example
   * // Get one ServiceFeatureMap
   * const serviceFeatureMap = await prisma.serviceFeatureMap.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends ServiceFeatureMapFindUniqueArgs>(args: Prisma.SelectSubset<T, ServiceFeatureMapFindUniqueArgs<ExtArgs>>): Prisma.Prisma__ServiceFeatureMapClient<runtime.Types.Result.GetResult<Prisma.$ServiceFeatureMapPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one ServiceFeatureMap that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {ServiceFeatureMapFindUniqueOrThrowArgs} args - Arguments to find a ServiceFeatureMap
   * @example
   * // Get one ServiceFeatureMap
   * const serviceFeatureMap = await prisma.serviceFeatureMap.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends ServiceFeatureMapFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, ServiceFeatureMapFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__ServiceFeatureMapClient<runtime.Types.Result.GetResult<Prisma.$ServiceFeatureMapPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ServiceFeatureMap that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ServiceFeatureMapFindFirstArgs} args - Arguments to find a ServiceFeatureMap
   * @example
   * // Get one ServiceFeatureMap
   * const serviceFeatureMap = await prisma.serviceFeatureMap.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends ServiceFeatureMapFindFirstArgs>(args?: Prisma.SelectSubset<T, ServiceFeatureMapFindFirstArgs<ExtArgs>>): Prisma.Prisma__ServiceFeatureMapClient<runtime.Types.Result.GetResult<Prisma.$ServiceFeatureMapPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ServiceFeatureMap that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ServiceFeatureMapFindFirstOrThrowArgs} args - Arguments to find a ServiceFeatureMap
   * @example
   * // Get one ServiceFeatureMap
   * const serviceFeatureMap = await prisma.serviceFeatureMap.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends ServiceFeatureMapFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, ServiceFeatureMapFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__ServiceFeatureMapClient<runtime.Types.Result.GetResult<Prisma.$ServiceFeatureMapPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more ServiceFeatureMaps that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ServiceFeatureMapFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all ServiceFeatureMaps
   * const serviceFeatureMaps = await prisma.serviceFeatureMap.findMany()
   * 
   * // Get first 10 ServiceFeatureMaps
   * const serviceFeatureMaps = await prisma.serviceFeatureMap.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const serviceFeatureMapWithIdOnly = await prisma.serviceFeatureMap.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends ServiceFeatureMapFindManyArgs>(args?: Prisma.SelectSubset<T, ServiceFeatureMapFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ServiceFeatureMapPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a ServiceFeatureMap.
   * @param {ServiceFeatureMapCreateArgs} args - Arguments to create a ServiceFeatureMap.
   * @example
   * // Create one ServiceFeatureMap
   * const ServiceFeatureMap = await prisma.serviceFeatureMap.create({
   *   data: {
   *     // ... data to create a ServiceFeatureMap
   *   }
   * })
   * 
   */
  create<T extends ServiceFeatureMapCreateArgs>(args: Prisma.SelectSubset<T, ServiceFeatureMapCreateArgs<ExtArgs>>): Prisma.Prisma__ServiceFeatureMapClient<runtime.Types.Result.GetResult<Prisma.$ServiceFeatureMapPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many ServiceFeatureMaps.
   * @param {ServiceFeatureMapCreateManyArgs} args - Arguments to create many ServiceFeatureMaps.
   * @example
   * // Create many ServiceFeatureMaps
   * const serviceFeatureMap = await prisma.serviceFeatureMap.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends ServiceFeatureMapCreateManyArgs>(args?: Prisma.SelectSubset<T, ServiceFeatureMapCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Delete a ServiceFeatureMap.
   * @param {ServiceFeatureMapDeleteArgs} args - Arguments to delete one ServiceFeatureMap.
   * @example
   * // Delete one ServiceFeatureMap
   * const ServiceFeatureMap = await prisma.serviceFeatureMap.delete({
   *   where: {
   *     // ... filter to delete one ServiceFeatureMap
   *   }
   * })
   * 
   */
  delete<T extends ServiceFeatureMapDeleteArgs>(args: Prisma.SelectSubset<T, ServiceFeatureMapDeleteArgs<ExtArgs>>): Prisma.Prisma__ServiceFeatureMapClient<runtime.Types.Result.GetResult<Prisma.$ServiceFeatureMapPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one ServiceFeatureMap.
   * @param {ServiceFeatureMapUpdateArgs} args - Arguments to update one ServiceFeatureMap.
   * @example
   * // Update one ServiceFeatureMap
   * const serviceFeatureMap = await prisma.serviceFeatureMap.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends ServiceFeatureMapUpdateArgs>(args: Prisma.SelectSubset<T, ServiceFeatureMapUpdateArgs<ExtArgs>>): Prisma.Prisma__ServiceFeatureMapClient<runtime.Types.Result.GetResult<Prisma.$ServiceFeatureMapPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more ServiceFeatureMaps.
   * @param {ServiceFeatureMapDeleteManyArgs} args - Arguments to filter ServiceFeatureMaps to delete.
   * @example
   * // Delete a few ServiceFeatureMaps
   * const { count } = await prisma.serviceFeatureMap.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends ServiceFeatureMapDeleteManyArgs>(args?: Prisma.SelectSubset<T, ServiceFeatureMapDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ServiceFeatureMaps.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ServiceFeatureMapUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many ServiceFeatureMaps
   * const serviceFeatureMap = await prisma.serviceFeatureMap.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends ServiceFeatureMapUpdateManyArgs>(args: Prisma.SelectSubset<T, ServiceFeatureMapUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create or update one ServiceFeatureMap.
   * @param {ServiceFeatureMapUpsertArgs} args - Arguments to update or create a ServiceFeatureMap.
   * @example
   * // Update or create a ServiceFeatureMap
   * const serviceFeatureMap = await prisma.serviceFeatureMap.upsert({
   *   create: {
   *     // ... data to create a ServiceFeatureMap
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the ServiceFeatureMap we want to update
   *   }
   * })
   */
  upsert<T extends ServiceFeatureMapUpsertArgs>(args: Prisma.SelectSubset<T, ServiceFeatureMapUpsertArgs<ExtArgs>>): Prisma.Prisma__ServiceFeatureMapClient<runtime.Types.Result.GetResult<Prisma.$ServiceFeatureMapPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of ServiceFeatureMaps.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ServiceFeatureMapCountArgs} args - Arguments to filter ServiceFeatureMaps to count.
   * @example
   * // Count the number of ServiceFeatureMaps
   * const count = await prisma.serviceFeatureMap.count({
   *   where: {
   *     // ... the filter for the ServiceFeatureMaps we want to count
   *   }
   * })
  **/
  count<T extends ServiceFeatureMapCountArgs>(
    args?: Prisma.Subset<T, ServiceFeatureMapCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], ServiceFeatureMapCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a ServiceFeatureMap.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ServiceFeatureMapAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends ServiceFeatureMapAggregateArgs>(args: Prisma.Subset<T, ServiceFeatureMapAggregateArgs>): Prisma.PrismaPromise<GetServiceFeatureMapAggregateType<T>>

  /**
   * Group by ServiceFeatureMap.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ServiceFeatureMapGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends ServiceFeatureMapGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: ServiceFeatureMapGroupByArgs['orderBy'] }
      : { orderBy?: ServiceFeatureMapGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, ServiceFeatureMapGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetServiceFeatureMapGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the ServiceFeatureMap model
 */
readonly fields: ServiceFeatureMapFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for ServiceFeatureMap.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__ServiceFeatureMapClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  service<T extends Prisma.ServiceDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ServiceDefaultArgs<ExtArgs>>): Prisma.Prisma__ServiceClient<runtime.Types.Result.GetResult<Prisma.$ServicePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  feature<T extends Prisma.ServiceFeatureDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ServiceFeatureDefaultArgs<ExtArgs>>): Prisma.Prisma__ServiceFeatureClient<runtime.Types.Result.GetResult<Prisma.$ServiceFeaturePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the ServiceFeatureMap model
 */
export interface ServiceFeatureMapFieldRefs {
  readonly id: Prisma.FieldRef<"ServiceFeatureMap", 'BigInt'>
  readonly serviceId: Prisma.FieldRef<"ServiceFeatureMap", 'BigInt'>
  readonly featureId: Prisma.FieldRef<"ServiceFeatureMap", 'BigInt'>
}
    

// Custom InputTypes
/**
 * ServiceFeatureMap findUnique
 */
export type ServiceFeatureMapFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ServiceFeatureMap
   */
  select?: Prisma.ServiceFeatureMapSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ServiceFeatureMap
   */
  omit?: Prisma.ServiceFeatureMapOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ServiceFeatureMapInclude<ExtArgs> | null
  /**
   * Filter, which ServiceFeatureMap to fetch.
   */
  where: Prisma.ServiceFeatureMapWhereUniqueInput
}

/**
 * ServiceFeatureMap findUniqueOrThrow
 */
export type ServiceFeatureMapFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ServiceFeatureMap
   */
  select?: Prisma.ServiceFeatureMapSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ServiceFeatureMap
   */
  omit?: Prisma.ServiceFeatureMapOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ServiceFeatureMapInclude<ExtArgs> | null
  /**
   * Filter, which ServiceFeatureMap to fetch.
   */
  where: Prisma.ServiceFeatureMapWhereUniqueInput
}

/**
 * ServiceFeatureMap findFirst
 */
export type ServiceFeatureMapFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ServiceFeatureMap
   */
  select?: Prisma.ServiceFeatureMapSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ServiceFeatureMap
   */
  omit?: Prisma.ServiceFeatureMapOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ServiceFeatureMapInclude<ExtArgs> | null
  /**
   * Filter, which ServiceFeatureMap to fetch.
   */
  where?: Prisma.ServiceFeatureMapWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ServiceFeatureMaps to fetch.
   */
  orderBy?: Prisma.ServiceFeatureMapOrderByWithRelationInput | Prisma.ServiceFeatureMapOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ServiceFeatureMaps.
   */
  cursor?: Prisma.ServiceFeatureMapWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ServiceFeatureMaps from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ServiceFeatureMaps.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ServiceFeatureMaps.
   */
  distinct?: Prisma.ServiceFeatureMapScalarFieldEnum | Prisma.ServiceFeatureMapScalarFieldEnum[]
}

/**
 * ServiceFeatureMap findFirstOrThrow
 */
export type ServiceFeatureMapFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ServiceFeatureMap
   */
  select?: Prisma.ServiceFeatureMapSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ServiceFeatureMap
   */
  omit?: Prisma.ServiceFeatureMapOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ServiceFeatureMapInclude<ExtArgs> | null
  /**
   * Filter, which ServiceFeatureMap to fetch.
   */
  where?: Prisma.ServiceFeatureMapWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ServiceFeatureMaps to fetch.
   */
  orderBy?: Prisma.ServiceFeatureMapOrderByWithRelationInput | Prisma.ServiceFeatureMapOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ServiceFeatureMaps.
   */
  cursor?: Prisma.ServiceFeatureMapWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ServiceFeatureMaps from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ServiceFeatureMaps.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ServiceFeatureMaps.
   */
  distinct?: Prisma.ServiceFeatureMapScalarFieldEnum | Prisma.ServiceFeatureMapScalarFieldEnum[]
}

/**
 * ServiceFeatureMap findMany
 */
export type ServiceFeatureMapFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ServiceFeatureMap
   */
  select?: Prisma.ServiceFeatureMapSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ServiceFeatureMap
   */
  omit?: Prisma.ServiceFeatureMapOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ServiceFeatureMapInclude<ExtArgs> | null
  /**
   * Filter, which ServiceFeatureMaps to fetch.
   */
  where?: Prisma.ServiceFeatureMapWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ServiceFeatureMaps to fetch.
   */
  orderBy?: Prisma.ServiceFeatureMapOrderByWithRelationInput | Prisma.ServiceFeatureMapOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing ServiceFeatureMaps.
   */
  cursor?: Prisma.ServiceFeatureMapWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ServiceFeatureMaps from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ServiceFeatureMaps.
   */
  skip?: number
  distinct?: Prisma.ServiceFeatureMapScalarFieldEnum | Prisma.ServiceFeatureMapScalarFieldEnum[]
}

/**
 * ServiceFeatureMap create
 */
export type ServiceFeatureMapCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ServiceFeatureMap
   */
  select?: Prisma.ServiceFeatureMapSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ServiceFeatureMap
   */
  omit?: Prisma.ServiceFeatureMapOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ServiceFeatureMapInclude<ExtArgs> | null
  /**
   * The data needed to create a ServiceFeatureMap.
   */
  data: Prisma.XOR<Prisma.ServiceFeatureMapCreateInput, Prisma.ServiceFeatureMapUncheckedCreateInput>
}

/**
 * ServiceFeatureMap createMany
 */
export type ServiceFeatureMapCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many ServiceFeatureMaps.
   */
  data: Prisma.ServiceFeatureMapCreateManyInput | Prisma.ServiceFeatureMapCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * ServiceFeatureMap update
 */
export type ServiceFeatureMapUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ServiceFeatureMap
   */
  select?: Prisma.ServiceFeatureMapSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ServiceFeatureMap
   */
  omit?: Prisma.ServiceFeatureMapOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ServiceFeatureMapInclude<ExtArgs> | null
  /**
   * The data needed to update a ServiceFeatureMap.
   */
  data: Prisma.XOR<Prisma.ServiceFeatureMapUpdateInput, Prisma.ServiceFeatureMapUncheckedUpdateInput>
  /**
   * Choose, which ServiceFeatureMap to update.
   */
  where: Prisma.ServiceFeatureMapWhereUniqueInput
}

/**
 * ServiceFeatureMap updateMany
 */
export type ServiceFeatureMapUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update ServiceFeatureMaps.
   */
  data: Prisma.XOR<Prisma.ServiceFeatureMapUpdateManyMutationInput, Prisma.ServiceFeatureMapUncheckedUpdateManyInput>
  /**
   * Filter which ServiceFeatureMaps to update
   */
  where?: Prisma.ServiceFeatureMapWhereInput
  /**
   * Limit how many ServiceFeatureMaps to update.
   */
  limit?: number
}

/**
 * ServiceFeatureMap upsert
 */
export type ServiceFeatureMapUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ServiceFeatureMap
   */
  select?: Prisma.ServiceFeatureMapSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ServiceFeatureMap
   */
  omit?: Prisma.ServiceFeatureMapOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ServiceFeatureMapInclude<ExtArgs> | null
  /**
   * The filter to search for the ServiceFeatureMap to update in case it exists.
   */
  where: Prisma.ServiceFeatureMapWhereUniqueInput
  /**
   * In case the ServiceFeatureMap found by the `where` argument doesn't exist, create a new ServiceFeatureMap with this data.
   */
  create: Prisma.XOR<Prisma.ServiceFeatureMapCreateInput, Prisma.ServiceFeatureMapUncheckedCreateInput>
  /**
   * In case the ServiceFeatureMap was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.ServiceFeatureMapUpdateInput, Prisma.ServiceFeatureMapUncheckedUpdateInput>
}

/**
 * ServiceFeatureMap delete
 */
export type ServiceFeatureMapDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ServiceFeatureMap
   */
  select?: Prisma.ServiceFeatureMapSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ServiceFeatureMap
   */
  omit?: Prisma.ServiceFeatureMapOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ServiceFeatureMapInclude<ExtArgs> | null
  /**
   * Filter which ServiceFeatureMap to delete.
   */
  where: Prisma.ServiceFeatureMapWhereUniqueInput
}

/**
 * ServiceFeatureMap deleteMany
 */
export type ServiceFeatureMapDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ServiceFeatureMaps to delete
   */
  where?: Prisma.ServiceFeatureMapWhereInput
  /**
   * Limit how many ServiceFeatureMaps to delete.
   */
  limit?: number
}

/**
 * ServiceFeatureMap without action
 */
export type ServiceFeatureMapDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ServiceFeatureMap
   */
  select?: Prisma.ServiceFeatureMapSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ServiceFeatureMap
   */
  omit?: Prisma.ServiceFeatureMapOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ServiceFeatureMapInclude<ExtArgs> | null
}
