
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Service` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model Service
 * 
 */
export type ServiceModel = runtime.Types.Result.DefaultSelection<Prisma.$ServicePayload>

export type AggregateService = {
  _count: ServiceCountAggregateOutputType | null
  _avg: ServiceAvgAggregateOutputType | null
  _sum: ServiceSumAggregateOutputType | null
  _min: ServiceMinAggregateOutputType | null
  _max: ServiceMaxAggregateOutputType | null
}

export type ServiceAvgAggregateOutputType = {
  id: number | null
  serviceCategoryId: number | null
  price: runtime.Decimal | null
  duration: number | null
}

export type ServiceSumAggregateOutputType = {
  id: number | null
  serviceCategoryId: number | null
  price: runtime.Decimal | null
  duration: number | null
}

export type ServiceMinAggregateOutputType = {
  id: number | null
  serviceCategoryId: number | null
  name: string | null
  price: runtime.Decimal | null
  duration: number | null
  createdAt: Date | null
  updatedAt: Date | null
  deletedAt: Date | null
}

export type ServiceMaxAggregateOutputType = {
  id: number | null
  serviceCategoryId: number | null
  name: string | null
  price: runtime.Decimal | null
  duration: number | null
  createdAt: Date | null
  updatedAt: Date | null
  deletedAt: Date | null
}

export type ServiceCountAggregateOutputType = {
  id: number
  serviceCategoryId: number
  name: number
  price: number
  duration: number
  createdAt: number
  updatedAt: number
  deletedAt: number
  _all: number
}


export type ServiceAvgAggregateInputType = {
  id?: true
  serviceCategoryId?: true
  price?: true
  duration?: true
}

export type ServiceSumAggregateInputType = {
  id?: true
  serviceCategoryId?: true
  price?: true
  duration?: true
}

export type ServiceMinAggregateInputType = {
  id?: true
  serviceCategoryId?: true
  name?: true
  price?: true
  duration?: true
  createdAt?: true
  updatedAt?: true
  deletedAt?: true
}

export type ServiceMaxAggregateInputType = {
  id?: true
  serviceCategoryId?: true
  name?: true
  price?: true
  duration?: true
  createdAt?: true
  updatedAt?: true
  deletedAt?: true
}

export type ServiceCountAggregateInputType = {
  id?: true
  serviceCategoryId?: true
  name?: true
  price?: true
  duration?: true
  createdAt?: true
  updatedAt?: true
  deletedAt?: true
  _all?: true
}

export type ServiceAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Service to aggregate.
   */
  where?: Prisma.ServiceWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Services to fetch.
   */
  orderBy?: Prisma.ServiceOrderByWithRelationInput | Prisma.ServiceOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.ServiceWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Services from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Services.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Services
  **/
  _count?: true | ServiceCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: ServiceAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: ServiceSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: ServiceMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: ServiceMaxAggregateInputType
}

export type GetServiceAggregateType<T extends ServiceAggregateArgs> = {
      [P in keyof T & keyof AggregateService]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateService[P]>
    : Prisma.GetScalarType<T[P], AggregateService[P]>
}




export type ServiceGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ServiceWhereInput
  orderBy?: Prisma.ServiceOrderByWithAggregationInput | Prisma.ServiceOrderByWithAggregationInput[]
  by: Prisma.ServiceScalarFieldEnum[] | Prisma.ServiceScalarFieldEnum
  having?: Prisma.ServiceScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: ServiceCountAggregateInputType | true
  _avg?: ServiceAvgAggregateInputType
  _sum?: ServiceSumAggregateInputType
  _min?: ServiceMinAggregateInputType
  _max?: ServiceMaxAggregateInputType
}

export type ServiceGroupByOutputType = {
  id: number
  serviceCategoryId: number
  name: string
  price: runtime.Decimal
  duration: number
  createdAt: Date
  updatedAt: Date
  deletedAt: Date | null
  _count: ServiceCountAggregateOutputType | null
  _avg: ServiceAvgAggregateOutputType | null
  _sum: ServiceSumAggregateOutputType | null
  _min: ServiceMinAggregateOutputType | null
  _max: ServiceMaxAggregateOutputType | null
}

type GetServiceGroupByPayload<T extends ServiceGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<ServiceGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof ServiceGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], ServiceGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], ServiceGroupByOutputType[P]>
      }
    >
  >



export type ServiceWhereInput = {
  AND?: Prisma.ServiceWhereInput | Prisma.ServiceWhereInput[]
  OR?: Prisma.ServiceWhereInput[]
  NOT?: Prisma.ServiceWhereInput | Prisma.ServiceWhereInput[]
  id?: Prisma.IntFilter<"Service"> | number
  serviceCategoryId?: Prisma.IntFilter<"Service"> | number
  name?: Prisma.StringFilter<"Service"> | string
  price?: Prisma.DecimalFilter<"Service"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  duration?: Prisma.IntFilter<"Service"> | number
  createdAt?: Prisma.DateTimeFilter<"Service"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Service"> | Date | string
  deletedAt?: Prisma.DateTimeNullableFilter<"Service"> | Date | string | null
  dateSlots?: Prisma.DateSlotListRelationFilter
  featureMaps?: Prisma.ServiceFeatureMapListRelationFilter
  serviceCategory?: Prisma.XOR<Prisma.ServiceCategoryScalarRelationFilter, Prisma.ServiceCategoryWhereInput>
}

export type ServiceOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  serviceCategoryId?: Prisma.SortOrder
  name?: Prisma.SortOrder
  price?: Prisma.SortOrder
  duration?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  deletedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  dateSlots?: Prisma.DateSlotOrderByRelationAggregateInput
  featureMaps?: Prisma.ServiceFeatureMapOrderByRelationAggregateInput
  serviceCategory?: Prisma.ServiceCategoryOrderByWithRelationInput
  _relevance?: Prisma.ServiceOrderByRelevanceInput
}

export type ServiceWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  AND?: Prisma.ServiceWhereInput | Prisma.ServiceWhereInput[]
  OR?: Prisma.ServiceWhereInput[]
  NOT?: Prisma.ServiceWhereInput | Prisma.ServiceWhereInput[]
  serviceCategoryId?: Prisma.IntFilter<"Service"> | number
  name?: Prisma.StringFilter<"Service"> | string
  price?: Prisma.DecimalFilter<"Service"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  duration?: Prisma.IntFilter<"Service"> | number
  createdAt?: Prisma.DateTimeFilter<"Service"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Service"> | Date | string
  deletedAt?: Prisma.DateTimeNullableFilter<"Service"> | Date | string | null
  dateSlots?: Prisma.DateSlotListRelationFilter
  featureMaps?: Prisma.ServiceFeatureMapListRelationFilter
  serviceCategory?: Prisma.XOR<Prisma.ServiceCategoryScalarRelationFilter, Prisma.ServiceCategoryWhereInput>
}, "id">

export type ServiceOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  serviceCategoryId?: Prisma.SortOrder
  name?: Prisma.SortOrder
  price?: Prisma.SortOrder
  duration?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  deletedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.ServiceCountOrderByAggregateInput
  _avg?: Prisma.ServiceAvgOrderByAggregateInput
  _max?: Prisma.ServiceMaxOrderByAggregateInput
  _min?: Prisma.ServiceMinOrderByAggregateInput
  _sum?: Prisma.ServiceSumOrderByAggregateInput
}

export type ServiceScalarWhereWithAggregatesInput = {
  AND?: Prisma.ServiceScalarWhereWithAggregatesInput | Prisma.ServiceScalarWhereWithAggregatesInput[]
  OR?: Prisma.ServiceScalarWhereWithAggregatesInput[]
  NOT?: Prisma.ServiceScalarWhereWithAggregatesInput | Prisma.ServiceScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"Service"> | number
  serviceCategoryId?: Prisma.IntWithAggregatesFilter<"Service"> | number
  name?: Prisma.StringWithAggregatesFilter<"Service"> | string
  price?: Prisma.DecimalWithAggregatesFilter<"Service"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  duration?: Prisma.IntWithAggregatesFilter<"Service"> | number
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"Service"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"Service"> | Date | string
  deletedAt?: Prisma.DateTimeNullableWithAggregatesFilter<"Service"> | Date | string | null
}

export type ServiceCreateInput = {
  name: string
  price: runtime.Decimal | runtime.DecimalJsLike | number | string
  duration: number
  createdAt?: Date | string
  updatedAt?: Date | string
  deletedAt?: Date | string | null
  dateSlots?: Prisma.DateSlotCreateNestedManyWithoutServiceInput
  featureMaps?: Prisma.ServiceFeatureMapCreateNestedManyWithoutServiceInput
  serviceCategory: Prisma.ServiceCategoryCreateNestedOneWithoutServicesInput
}

export type ServiceUncheckedCreateInput = {
  id?: number
  serviceCategoryId: number
  name: string
  price: runtime.Decimal | runtime.DecimalJsLike | number | string
  duration: number
  createdAt?: Date | string
  updatedAt?: Date | string
  deletedAt?: Date | string | null
  dateSlots?: Prisma.DateSlotUncheckedCreateNestedManyWithoutServiceInput
  featureMaps?: Prisma.ServiceFeatureMapUncheckedCreateNestedManyWithoutServiceInput
}

export type ServiceUpdateInput = {
  name?: Prisma.StringFieldUpdateOperationsInput | string
  price?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  duration?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  dateSlots?: Prisma.DateSlotUpdateManyWithoutServiceNestedInput
  featureMaps?: Prisma.ServiceFeatureMapUpdateManyWithoutServiceNestedInput
  serviceCategory?: Prisma.ServiceCategoryUpdateOneRequiredWithoutServicesNestedInput
}

export type ServiceUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  serviceCategoryId?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  price?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  duration?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  dateSlots?: Prisma.DateSlotUncheckedUpdateManyWithoutServiceNestedInput
  featureMaps?: Prisma.ServiceFeatureMapUncheckedUpdateManyWithoutServiceNestedInput
}

export type ServiceCreateManyInput = {
  id?: number
  serviceCategoryId: number
  name: string
  price: runtime.Decimal | runtime.DecimalJsLike | number | string
  duration: number
  createdAt?: Date | string
  updatedAt?: Date | string
  deletedAt?: Date | string | null
}

export type ServiceUpdateManyMutationInput = {
  name?: Prisma.StringFieldUpdateOperationsInput | string
  price?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  duration?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type ServiceUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  serviceCategoryId?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  price?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  duration?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type ServiceListRelationFilter = {
  every?: Prisma.ServiceWhereInput
  some?: Prisma.ServiceWhereInput
  none?: Prisma.ServiceWhereInput
}

export type ServiceOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type ServiceOrderByRelevanceInput = {
  fields: Prisma.ServiceOrderByRelevanceFieldEnum | Prisma.ServiceOrderByRelevanceFieldEnum[]
  sort: Prisma.SortOrder
  search: string
}

export type ServiceCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  serviceCategoryId?: Prisma.SortOrder
  name?: Prisma.SortOrder
  price?: Prisma.SortOrder
  duration?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  deletedAt?: Prisma.SortOrder
}

export type ServiceAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
  serviceCategoryId?: Prisma.SortOrder
  price?: Prisma.SortOrder
  duration?: Prisma.SortOrder
}

export type ServiceMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  serviceCategoryId?: Prisma.SortOrder
  name?: Prisma.SortOrder
  price?: Prisma.SortOrder
  duration?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  deletedAt?: Prisma.SortOrder
}

export type ServiceMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  serviceCategoryId?: Prisma.SortOrder
  name?: Prisma.SortOrder
  price?: Prisma.SortOrder
  duration?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  deletedAt?: Prisma.SortOrder
}

export type ServiceSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
  serviceCategoryId?: Prisma.SortOrder
  price?: Prisma.SortOrder
  duration?: Prisma.SortOrder
}

export type ServiceScalarRelationFilter = {
  is?: Prisma.ServiceWhereInput
  isNot?: Prisma.ServiceWhereInput
}

export type ServiceCreateNestedManyWithoutServiceCategoryInput = {
  create?: Prisma.XOR<Prisma.ServiceCreateWithoutServiceCategoryInput, Prisma.ServiceUncheckedCreateWithoutServiceCategoryInput> | Prisma.ServiceCreateWithoutServiceCategoryInput[] | Prisma.ServiceUncheckedCreateWithoutServiceCategoryInput[]
  connectOrCreate?: Prisma.ServiceCreateOrConnectWithoutServiceCategoryInput | Prisma.ServiceCreateOrConnectWithoutServiceCategoryInput[]
  createMany?: Prisma.ServiceCreateManyServiceCategoryInputEnvelope
  connect?: Prisma.ServiceWhereUniqueInput | Prisma.ServiceWhereUniqueInput[]
}

export type ServiceUncheckedCreateNestedManyWithoutServiceCategoryInput = {
  create?: Prisma.XOR<Prisma.ServiceCreateWithoutServiceCategoryInput, Prisma.ServiceUncheckedCreateWithoutServiceCategoryInput> | Prisma.ServiceCreateWithoutServiceCategoryInput[] | Prisma.ServiceUncheckedCreateWithoutServiceCategoryInput[]
  connectOrCreate?: Prisma.ServiceCreateOrConnectWithoutServiceCategoryInput | Prisma.ServiceCreateOrConnectWithoutServiceCategoryInput[]
  createMany?: Prisma.ServiceCreateManyServiceCategoryInputEnvelope
  connect?: Prisma.ServiceWhereUniqueInput | Prisma.ServiceWhereUniqueInput[]
}

export type ServiceUpdateManyWithoutServiceCategoryNestedInput = {
  create?: Prisma.XOR<Prisma.ServiceCreateWithoutServiceCategoryInput, Prisma.ServiceUncheckedCreateWithoutServiceCategoryInput> | Prisma.ServiceCreateWithoutServiceCategoryInput[] | Prisma.ServiceUncheckedCreateWithoutServiceCategoryInput[]
  connectOrCreate?: Prisma.ServiceCreateOrConnectWithoutServiceCategoryInput | Prisma.ServiceCreateOrConnectWithoutServiceCategoryInput[]
  upsert?: Prisma.ServiceUpsertWithWhereUniqueWithoutServiceCategoryInput | Prisma.ServiceUpsertWithWhereUniqueWithoutServiceCategoryInput[]
  createMany?: Prisma.ServiceCreateManyServiceCategoryInputEnvelope
  set?: Prisma.ServiceWhereUniqueInput | Prisma.ServiceWhereUniqueInput[]
  disconnect?: Prisma.ServiceWhereUniqueInput | Prisma.ServiceWhereUniqueInput[]
  delete?: Prisma.ServiceWhereUniqueInput | Prisma.ServiceWhereUniqueInput[]
  connect?: Prisma.ServiceWhereUniqueInput | Prisma.ServiceWhereUniqueInput[]
  update?: Prisma.ServiceUpdateWithWhereUniqueWithoutServiceCategoryInput | Prisma.ServiceUpdateWithWhereUniqueWithoutServiceCategoryInput[]
  updateMany?: Prisma.ServiceUpdateManyWithWhereWithoutServiceCategoryInput | Prisma.ServiceUpdateManyWithWhereWithoutServiceCategoryInput[]
  deleteMany?: Prisma.ServiceScalarWhereInput | Prisma.ServiceScalarWhereInput[]
}

export type ServiceUncheckedUpdateManyWithoutServiceCategoryNestedInput = {
  create?: Prisma.XOR<Prisma.ServiceCreateWithoutServiceCategoryInput, Prisma.ServiceUncheckedCreateWithoutServiceCategoryInput> | Prisma.ServiceCreateWithoutServiceCategoryInput[] | Prisma.ServiceUncheckedCreateWithoutServiceCategoryInput[]
  connectOrCreate?: Prisma.ServiceCreateOrConnectWithoutServiceCategoryInput | Prisma.ServiceCreateOrConnectWithoutServiceCategoryInput[]
  upsert?: Prisma.ServiceUpsertWithWhereUniqueWithoutServiceCategoryInput | Prisma.ServiceUpsertWithWhereUniqueWithoutServiceCategoryInput[]
  createMany?: Prisma.ServiceCreateManyServiceCategoryInputEnvelope
  set?: Prisma.ServiceWhereUniqueInput | Prisma.ServiceWhereUniqueInput[]
  disconnect?: Prisma.ServiceWhereUniqueInput | Prisma.ServiceWhereUniqueInput[]
  delete?: Prisma.ServiceWhereUniqueInput | Prisma.ServiceWhereUniqueInput[]
  connect?: Prisma.ServiceWhereUniqueInput | Prisma.ServiceWhereUniqueInput[]
  update?: Prisma.ServiceUpdateWithWhereUniqueWithoutServiceCategoryInput | Prisma.ServiceUpdateWithWhereUniqueWithoutServiceCategoryInput[]
  updateMany?: Prisma.ServiceUpdateManyWithWhereWithoutServiceCategoryInput | Prisma.ServiceUpdateManyWithWhereWithoutServiceCategoryInput[]
  deleteMany?: Prisma.ServiceScalarWhereInput | Prisma.ServiceScalarWhereInput[]
}

export type DecimalFieldUpdateOperationsInput = {
  set?: runtime.Decimal | runtime.DecimalJsLike | number | string
  increment?: runtime.Decimal | runtime.DecimalJsLike | number | string
  decrement?: runtime.Decimal | runtime.DecimalJsLike | number | string
  multiply?: runtime.Decimal | runtime.DecimalJsLike | number | string
  divide?: runtime.Decimal | runtime.DecimalJsLike | number | string
}

export type ServiceCreateNestedOneWithoutFeatureMapsInput = {
  create?: Prisma.XOR<Prisma.ServiceCreateWithoutFeatureMapsInput, Prisma.ServiceUncheckedCreateWithoutFeatureMapsInput>
  connectOrCreate?: Prisma.ServiceCreateOrConnectWithoutFeatureMapsInput
  connect?: Prisma.ServiceWhereUniqueInput
}

export type ServiceUpdateOneRequiredWithoutFeatureMapsNestedInput = {
  create?: Prisma.XOR<Prisma.ServiceCreateWithoutFeatureMapsInput, Prisma.ServiceUncheckedCreateWithoutFeatureMapsInput>
  connectOrCreate?: Prisma.ServiceCreateOrConnectWithoutFeatureMapsInput
  upsert?: Prisma.ServiceUpsertWithoutFeatureMapsInput
  connect?: Prisma.ServiceWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.ServiceUpdateToOneWithWhereWithoutFeatureMapsInput, Prisma.ServiceUpdateWithoutFeatureMapsInput>, Prisma.ServiceUncheckedUpdateWithoutFeatureMapsInput>
}

export type ServiceCreateNestedOneWithoutDateSlotsInput = {
  create?: Prisma.XOR<Prisma.ServiceCreateWithoutDateSlotsInput, Prisma.ServiceUncheckedCreateWithoutDateSlotsInput>
  connectOrCreate?: Prisma.ServiceCreateOrConnectWithoutDateSlotsInput
  connect?: Prisma.ServiceWhereUniqueInput
}

export type ServiceUpdateOneRequiredWithoutDateSlotsNestedInput = {
  create?: Prisma.XOR<Prisma.ServiceCreateWithoutDateSlotsInput, Prisma.ServiceUncheckedCreateWithoutDateSlotsInput>
  connectOrCreate?: Prisma.ServiceCreateOrConnectWithoutDateSlotsInput
  upsert?: Prisma.ServiceUpsertWithoutDateSlotsInput
  connect?: Prisma.ServiceWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.ServiceUpdateToOneWithWhereWithoutDateSlotsInput, Prisma.ServiceUpdateWithoutDateSlotsInput>, Prisma.ServiceUncheckedUpdateWithoutDateSlotsInput>
}

export type ServiceCreateWithoutServiceCategoryInput = {
  name: string
  price: runtime.Decimal | runtime.DecimalJsLike | number | string
  duration: number
  createdAt?: Date | string
  updatedAt?: Date | string
  deletedAt?: Date | string | null
  dateSlots?: Prisma.DateSlotCreateNestedManyWithoutServiceInput
  featureMaps?: Prisma.ServiceFeatureMapCreateNestedManyWithoutServiceInput
}

export type ServiceUncheckedCreateWithoutServiceCategoryInput = {
  id?: number
  name: string
  price: runtime.Decimal | runtime.DecimalJsLike | number | string
  duration: number
  createdAt?: Date | string
  updatedAt?: Date | string
  deletedAt?: Date | string | null
  dateSlots?: Prisma.DateSlotUncheckedCreateNestedManyWithoutServiceInput
  featureMaps?: Prisma.ServiceFeatureMapUncheckedCreateNestedManyWithoutServiceInput
}

export type ServiceCreateOrConnectWithoutServiceCategoryInput = {
  where: Prisma.ServiceWhereUniqueInput
  create: Prisma.XOR<Prisma.ServiceCreateWithoutServiceCategoryInput, Prisma.ServiceUncheckedCreateWithoutServiceCategoryInput>
}

export type ServiceCreateManyServiceCategoryInputEnvelope = {
  data: Prisma.ServiceCreateManyServiceCategoryInput | Prisma.ServiceCreateManyServiceCategoryInput[]
  skipDuplicates?: boolean
}

export type ServiceUpsertWithWhereUniqueWithoutServiceCategoryInput = {
  where: Prisma.ServiceWhereUniqueInput
  update: Prisma.XOR<Prisma.ServiceUpdateWithoutServiceCategoryInput, Prisma.ServiceUncheckedUpdateWithoutServiceCategoryInput>
  create: Prisma.XOR<Prisma.ServiceCreateWithoutServiceCategoryInput, Prisma.ServiceUncheckedCreateWithoutServiceCategoryInput>
}

export type ServiceUpdateWithWhereUniqueWithoutServiceCategoryInput = {
  where: Prisma.ServiceWhereUniqueInput
  data: Prisma.XOR<Prisma.ServiceUpdateWithoutServiceCategoryInput, Prisma.ServiceUncheckedUpdateWithoutServiceCategoryInput>
}

export type ServiceUpdateManyWithWhereWithoutServiceCategoryInput = {
  where: Prisma.ServiceScalarWhereInput
  data: Prisma.XOR<Prisma.ServiceUpdateManyMutationInput, Prisma.ServiceUncheckedUpdateManyWithoutServiceCategoryInput>
}

export type ServiceScalarWhereInput = {
  AND?: Prisma.ServiceScalarWhereInput | Prisma.ServiceScalarWhereInput[]
  OR?: Prisma.ServiceScalarWhereInput[]
  NOT?: Prisma.ServiceScalarWhereInput | Prisma.ServiceScalarWhereInput[]
  id?: Prisma.IntFilter<"Service"> | number
  serviceCategoryId?: Prisma.IntFilter<"Service"> | number
  name?: Prisma.StringFilter<"Service"> | string
  price?: Prisma.DecimalFilter<"Service"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  duration?: Prisma.IntFilter<"Service"> | number
  createdAt?: Prisma.DateTimeFilter<"Service"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Service"> | Date | string
  deletedAt?: Prisma.DateTimeNullableFilter<"Service"> | Date | string | null
}

export type ServiceCreateWithoutFeatureMapsInput = {
  name: string
  price: runtime.Decimal | runtime.DecimalJsLike | number | string
  duration: number
  createdAt?: Date | string
  updatedAt?: Date | string
  deletedAt?: Date | string | null
  dateSlots?: Prisma.DateSlotCreateNestedManyWithoutServiceInput
  serviceCategory: Prisma.ServiceCategoryCreateNestedOneWithoutServicesInput
}

export type ServiceUncheckedCreateWithoutFeatureMapsInput = {
  id?: number
  serviceCategoryId: number
  name: string
  price: runtime.Decimal | runtime.DecimalJsLike | number | string
  duration: number
  createdAt?: Date | string
  updatedAt?: Date | string
  deletedAt?: Date | string | null
  dateSlots?: Prisma.DateSlotUncheckedCreateNestedManyWithoutServiceInput
}

export type ServiceCreateOrConnectWithoutFeatureMapsInput = {
  where: Prisma.ServiceWhereUniqueInput
  create: Prisma.XOR<Prisma.ServiceCreateWithoutFeatureMapsInput, Prisma.ServiceUncheckedCreateWithoutFeatureMapsInput>
}

export type ServiceUpsertWithoutFeatureMapsInput = {
  update: Prisma.XOR<Prisma.ServiceUpdateWithoutFeatureMapsInput, Prisma.ServiceUncheckedUpdateWithoutFeatureMapsInput>
  create: Prisma.XOR<Prisma.ServiceCreateWithoutFeatureMapsInput, Prisma.ServiceUncheckedCreateWithoutFeatureMapsInput>
  where?: Prisma.ServiceWhereInput
}

export type ServiceUpdateToOneWithWhereWithoutFeatureMapsInput = {
  where?: Prisma.ServiceWhereInput
  data: Prisma.XOR<Prisma.ServiceUpdateWithoutFeatureMapsInput, Prisma.ServiceUncheckedUpdateWithoutFeatureMapsInput>
}

export type ServiceUpdateWithoutFeatureMapsInput = {
  name?: Prisma.StringFieldUpdateOperationsInput | string
  price?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  duration?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  dateSlots?: Prisma.DateSlotUpdateManyWithoutServiceNestedInput
  serviceCategory?: Prisma.ServiceCategoryUpdateOneRequiredWithoutServicesNestedInput
}

export type ServiceUncheckedUpdateWithoutFeatureMapsInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  serviceCategoryId?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  price?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  duration?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  dateSlots?: Prisma.DateSlotUncheckedUpdateManyWithoutServiceNestedInput
}

export type ServiceCreateWithoutDateSlotsInput = {
  name: string
  price: runtime.Decimal | runtime.DecimalJsLike | number | string
  duration: number
  createdAt?: Date | string
  updatedAt?: Date | string
  deletedAt?: Date | string | null
  featureMaps?: Prisma.ServiceFeatureMapCreateNestedManyWithoutServiceInput
  serviceCategory: Prisma.ServiceCategoryCreateNestedOneWithoutServicesInput
}

export type ServiceUncheckedCreateWithoutDateSlotsInput = {
  id?: number
  serviceCategoryId: number
  name: string
  price: runtime.Decimal | runtime.DecimalJsLike | number | string
  duration: number
  createdAt?: Date | string
  updatedAt?: Date | string
  deletedAt?: Date | string | null
  featureMaps?: Prisma.ServiceFeatureMapUncheckedCreateNestedManyWithoutServiceInput
}

export type ServiceCreateOrConnectWithoutDateSlotsInput = {
  where: Prisma.ServiceWhereUniqueInput
  create: Prisma.XOR<Prisma.ServiceCreateWithoutDateSlotsInput, Prisma.ServiceUncheckedCreateWithoutDateSlotsInput>
}

export type ServiceUpsertWithoutDateSlotsInput = {
  update: Prisma.XOR<Prisma.ServiceUpdateWithoutDateSlotsInput, Prisma.ServiceUncheckedUpdateWithoutDateSlotsInput>
  create: Prisma.XOR<Prisma.ServiceCreateWithoutDateSlotsInput, Prisma.ServiceUncheckedCreateWithoutDateSlotsInput>
  where?: Prisma.ServiceWhereInput
}

export type ServiceUpdateToOneWithWhereWithoutDateSlotsInput = {
  where?: Prisma.ServiceWhereInput
  data: Prisma.XOR<Prisma.ServiceUpdateWithoutDateSlotsInput, Prisma.ServiceUncheckedUpdateWithoutDateSlotsInput>
}

export type ServiceUpdateWithoutDateSlotsInput = {
  name?: Prisma.StringFieldUpdateOperationsInput | string
  price?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  duration?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  featureMaps?: Prisma.ServiceFeatureMapUpdateManyWithoutServiceNestedInput
  serviceCategory?: Prisma.ServiceCategoryUpdateOneRequiredWithoutServicesNestedInput
}

export type ServiceUncheckedUpdateWithoutDateSlotsInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  serviceCategoryId?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  price?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  duration?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  featureMaps?: Prisma.ServiceFeatureMapUncheckedUpdateManyWithoutServiceNestedInput
}

export type ServiceCreateManyServiceCategoryInput = {
  id?: number
  name: string
  price: runtime.Decimal | runtime.DecimalJsLike | number | string
  duration: number
  createdAt?: Date | string
  updatedAt?: Date | string
  deletedAt?: Date | string | null
}

export type ServiceUpdateWithoutServiceCategoryInput = {
  name?: Prisma.StringFieldUpdateOperationsInput | string
  price?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  duration?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  dateSlots?: Prisma.DateSlotUpdateManyWithoutServiceNestedInput
  featureMaps?: Prisma.ServiceFeatureMapUpdateManyWithoutServiceNestedInput
}

export type ServiceUncheckedUpdateWithoutServiceCategoryInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  price?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  duration?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  dateSlots?: Prisma.DateSlotUncheckedUpdateManyWithoutServiceNestedInput
  featureMaps?: Prisma.ServiceFeatureMapUncheckedUpdateManyWithoutServiceNestedInput
}

export type ServiceUncheckedUpdateManyWithoutServiceCategoryInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  price?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  duration?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}


/**
 * Count Type ServiceCountOutputType
 */

export type ServiceCountOutputType = {
  dateSlots: number
  featureMaps: number
}

export type ServiceCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  dateSlots?: boolean | ServiceCountOutputTypeCountDateSlotsArgs
  featureMaps?: boolean | ServiceCountOutputTypeCountFeatureMapsArgs
}

/**
 * ServiceCountOutputType without action
 */
export type ServiceCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ServiceCountOutputType
   */
  select?: Prisma.ServiceCountOutputTypeSelect<ExtArgs> | null
}

/**
 * ServiceCountOutputType without action
 */
export type ServiceCountOutputTypeCountDateSlotsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.DateSlotWhereInput
}

/**
 * ServiceCountOutputType without action
 */
export type ServiceCountOutputTypeCountFeatureMapsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ServiceFeatureMapWhereInput
}


export type ServiceSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  serviceCategoryId?: boolean
  name?: boolean
  price?: boolean
  duration?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  deletedAt?: boolean
  dateSlots?: boolean | Prisma.Service$dateSlotsArgs<ExtArgs>
  featureMaps?: boolean | Prisma.Service$featureMapsArgs<ExtArgs>
  serviceCategory?: boolean | Prisma.ServiceCategoryDefaultArgs<ExtArgs>
  _count?: boolean | Prisma.ServiceCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["service"]>



export type ServiceSelectScalar = {
  id?: boolean
  serviceCategoryId?: boolean
  name?: boolean
  price?: boolean
  duration?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  deletedAt?: boolean
}

export type ServiceOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "serviceCategoryId" | "name" | "price" | "duration" | "createdAt" | "updatedAt" | "deletedAt", ExtArgs["result"]["service"]>
export type ServiceInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  dateSlots?: boolean | Prisma.Service$dateSlotsArgs<ExtArgs>
  featureMaps?: boolean | Prisma.Service$featureMapsArgs<ExtArgs>
  serviceCategory?: boolean | Prisma.ServiceCategoryDefaultArgs<ExtArgs>
  _count?: boolean | Prisma.ServiceCountOutputTypeDefaultArgs<ExtArgs>
}

export type $ServicePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Service"
  objects: {
    dateSlots: Prisma.$DateSlotPayload<ExtArgs>[]
    featureMaps: Prisma.$ServiceFeatureMapPayload<ExtArgs>[]
    serviceCategory: Prisma.$ServiceCategoryPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    serviceCategoryId: number
    name: string
    price: runtime.Decimal
    duration: number
    createdAt: Date
    updatedAt: Date
    deletedAt: Date | null
  }, ExtArgs["result"]["service"]>
  composites: {}
}

export type ServiceGetPayload<S extends boolean | null | undefined | ServiceDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$ServicePayload, S>

export type ServiceCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<ServiceFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: ServiceCountAggregateInputType | true
  }

export interface ServiceDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Service'], meta: { name: 'Service' } }
  /**
   * Find zero or one Service that matches the filter.
   * @param {ServiceFindUniqueArgs} args - Arguments to find a Service
   * @example
   * // Get one Service
   * const service = await prisma.service.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends ServiceFindUniqueArgs>(args: Prisma.SelectSubset<T, ServiceFindUniqueArgs<ExtArgs>>): Prisma.Prisma__ServiceClient<runtime.Types.Result.GetResult<Prisma.$ServicePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Service that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {ServiceFindUniqueOrThrowArgs} args - Arguments to find a Service
   * @example
   * // Get one Service
   * const service = await prisma.service.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends ServiceFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, ServiceFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__ServiceClient<runtime.Types.Result.GetResult<Prisma.$ServicePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Service that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ServiceFindFirstArgs} args - Arguments to find a Service
   * @example
   * // Get one Service
   * const service = await prisma.service.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends ServiceFindFirstArgs>(args?: Prisma.SelectSubset<T, ServiceFindFirstArgs<ExtArgs>>): Prisma.Prisma__ServiceClient<runtime.Types.Result.GetResult<Prisma.$ServicePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Service that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ServiceFindFirstOrThrowArgs} args - Arguments to find a Service
   * @example
   * // Get one Service
   * const service = await prisma.service.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends ServiceFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, ServiceFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__ServiceClient<runtime.Types.Result.GetResult<Prisma.$ServicePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Services that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ServiceFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Services
   * const services = await prisma.service.findMany()
   * 
   * // Get first 10 Services
   * const services = await prisma.service.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const serviceWithIdOnly = await prisma.service.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends ServiceFindManyArgs>(args?: Prisma.SelectSubset<T, ServiceFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ServicePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Service.
   * @param {ServiceCreateArgs} args - Arguments to create a Service.
   * @example
   * // Create one Service
   * const Service = await prisma.service.create({
   *   data: {
   *     // ... data to create a Service
   *   }
   * })
   * 
   */
  create<T extends ServiceCreateArgs>(args: Prisma.SelectSubset<T, ServiceCreateArgs<ExtArgs>>): Prisma.Prisma__ServiceClient<runtime.Types.Result.GetResult<Prisma.$ServicePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Services.
   * @param {ServiceCreateManyArgs} args - Arguments to create many Services.
   * @example
   * // Create many Services
   * const service = await prisma.service.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends ServiceCreateManyArgs>(args?: Prisma.SelectSubset<T, ServiceCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Delete a Service.
   * @param {ServiceDeleteArgs} args - Arguments to delete one Service.
   * @example
   * // Delete one Service
   * const Service = await prisma.service.delete({
   *   where: {
   *     // ... filter to delete one Service
   *   }
   * })
   * 
   */
  delete<T extends ServiceDeleteArgs>(args: Prisma.SelectSubset<T, ServiceDeleteArgs<ExtArgs>>): Prisma.Prisma__ServiceClient<runtime.Types.Result.GetResult<Prisma.$ServicePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Service.
   * @param {ServiceUpdateArgs} args - Arguments to update one Service.
   * @example
   * // Update one Service
   * const service = await prisma.service.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends ServiceUpdateArgs>(args: Prisma.SelectSubset<T, ServiceUpdateArgs<ExtArgs>>): Prisma.Prisma__ServiceClient<runtime.Types.Result.GetResult<Prisma.$ServicePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Services.
   * @param {ServiceDeleteManyArgs} args - Arguments to filter Services to delete.
   * @example
   * // Delete a few Services
   * const { count } = await prisma.service.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends ServiceDeleteManyArgs>(args?: Prisma.SelectSubset<T, ServiceDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Services.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ServiceUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Services
   * const service = await prisma.service.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends ServiceUpdateManyArgs>(args: Prisma.SelectSubset<T, ServiceUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create or update one Service.
   * @param {ServiceUpsertArgs} args - Arguments to update or create a Service.
   * @example
   * // Update or create a Service
   * const service = await prisma.service.upsert({
   *   create: {
   *     // ... data to create a Service
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Service we want to update
   *   }
   * })
   */
  upsert<T extends ServiceUpsertArgs>(args: Prisma.SelectSubset<T, ServiceUpsertArgs<ExtArgs>>): Prisma.Prisma__ServiceClient<runtime.Types.Result.GetResult<Prisma.$ServicePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Services.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ServiceCountArgs} args - Arguments to filter Services to count.
   * @example
   * // Count the number of Services
   * const count = await prisma.service.count({
   *   where: {
   *     // ... the filter for the Services we want to count
   *   }
   * })
  **/
  count<T extends ServiceCountArgs>(
    args?: Prisma.Subset<T, ServiceCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], ServiceCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Service.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ServiceAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends ServiceAggregateArgs>(args: Prisma.Subset<T, ServiceAggregateArgs>): Prisma.PrismaPromise<GetServiceAggregateType<T>>

  /**
   * Group by Service.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ServiceGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends ServiceGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: ServiceGroupByArgs['orderBy'] }
      : { orderBy?: ServiceGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, ServiceGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetServiceGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Service model
 */
readonly fields: ServiceFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Service.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__ServiceClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  dateSlots<T extends Prisma.Service$dateSlotsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Service$dateSlotsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$DateSlotPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  featureMaps<T extends Prisma.Service$featureMapsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Service$featureMapsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ServiceFeatureMapPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  serviceCategory<T extends Prisma.ServiceCategoryDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ServiceCategoryDefaultArgs<ExtArgs>>): Prisma.Prisma__ServiceCategoryClient<runtime.Types.Result.GetResult<Prisma.$ServiceCategoryPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Service model
 */
export interface ServiceFieldRefs {
  readonly id: Prisma.FieldRef<"Service", 'Int'>
  readonly serviceCategoryId: Prisma.FieldRef<"Service", 'Int'>
  readonly name: Prisma.FieldRef<"Service", 'String'>
  readonly price: Prisma.FieldRef<"Service", 'Decimal'>
  readonly duration: Prisma.FieldRef<"Service", 'Int'>
  readonly createdAt: Prisma.FieldRef<"Service", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"Service", 'DateTime'>
  readonly deletedAt: Prisma.FieldRef<"Service", 'DateTime'>
}
    

// Custom InputTypes
/**
 * Service findUnique
 */
export type ServiceFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Service
   */
  select?: Prisma.ServiceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Service
   */
  omit?: Prisma.ServiceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ServiceInclude<ExtArgs> | null
  /**
   * Filter, which Service to fetch.
   */
  where: Prisma.ServiceWhereUniqueInput
}

/**
 * Service findUniqueOrThrow
 */
export type ServiceFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Service
   */
  select?: Prisma.ServiceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Service
   */
  omit?: Prisma.ServiceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ServiceInclude<ExtArgs> | null
  /**
   * Filter, which Service to fetch.
   */
  where: Prisma.ServiceWhereUniqueInput
}

/**
 * Service findFirst
 */
export type ServiceFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Service
   */
  select?: Prisma.ServiceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Service
   */
  omit?: Prisma.ServiceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ServiceInclude<ExtArgs> | null
  /**
   * Filter, which Service to fetch.
   */
  where?: Prisma.ServiceWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Services to fetch.
   */
  orderBy?: Prisma.ServiceOrderByWithRelationInput | Prisma.ServiceOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Services.
   */
  cursor?: Prisma.ServiceWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Services from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Services.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Services.
   */
  distinct?: Prisma.ServiceScalarFieldEnum | Prisma.ServiceScalarFieldEnum[]
}

/**
 * Service findFirstOrThrow
 */
export type ServiceFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Service
   */
  select?: Prisma.ServiceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Service
   */
  omit?: Prisma.ServiceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ServiceInclude<ExtArgs> | null
  /**
   * Filter, which Service to fetch.
   */
  where?: Prisma.ServiceWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Services to fetch.
   */
  orderBy?: Prisma.ServiceOrderByWithRelationInput | Prisma.ServiceOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Services.
   */
  cursor?: Prisma.ServiceWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Services from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Services.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Services.
   */
  distinct?: Prisma.ServiceScalarFieldEnum | Prisma.ServiceScalarFieldEnum[]
}

/**
 * Service findMany
 */
export type ServiceFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Service
   */
  select?: Prisma.ServiceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Service
   */
  omit?: Prisma.ServiceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ServiceInclude<ExtArgs> | null
  /**
   * Filter, which Services to fetch.
   */
  where?: Prisma.ServiceWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Services to fetch.
   */
  orderBy?: Prisma.ServiceOrderByWithRelationInput | Prisma.ServiceOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Services.
   */
  cursor?: Prisma.ServiceWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Services from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Services.
   */
  skip?: number
  distinct?: Prisma.ServiceScalarFieldEnum | Prisma.ServiceScalarFieldEnum[]
}

/**
 * Service create
 */
export type ServiceCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Service
   */
  select?: Prisma.ServiceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Service
   */
  omit?: Prisma.ServiceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ServiceInclude<ExtArgs> | null
  /**
   * The data needed to create a Service.
   */
  data: Prisma.XOR<Prisma.ServiceCreateInput, Prisma.ServiceUncheckedCreateInput>
}

/**
 * Service createMany
 */
export type ServiceCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Services.
   */
  data: Prisma.ServiceCreateManyInput | Prisma.ServiceCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Service update
 */
export type ServiceUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Service
   */
  select?: Prisma.ServiceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Service
   */
  omit?: Prisma.ServiceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ServiceInclude<ExtArgs> | null
  /**
   * The data needed to update a Service.
   */
  data: Prisma.XOR<Prisma.ServiceUpdateInput, Prisma.ServiceUncheckedUpdateInput>
  /**
   * Choose, which Service to update.
   */
  where: Prisma.ServiceWhereUniqueInput
}

/**
 * Service updateMany
 */
export type ServiceUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Services.
   */
  data: Prisma.XOR<Prisma.ServiceUpdateManyMutationInput, Prisma.ServiceUncheckedUpdateManyInput>
  /**
   * Filter which Services to update
   */
  where?: Prisma.ServiceWhereInput
  /**
   * Limit how many Services to update.
   */
  limit?: number
}

/**
 * Service upsert
 */
export type ServiceUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Service
   */
  select?: Prisma.ServiceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Service
   */
  omit?: Prisma.ServiceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ServiceInclude<ExtArgs> | null
  /**
   * The filter to search for the Service to update in case it exists.
   */
  where: Prisma.ServiceWhereUniqueInput
  /**
   * In case the Service found by the `where` argument doesn't exist, create a new Service with this data.
   */
  create: Prisma.XOR<Prisma.ServiceCreateInput, Prisma.ServiceUncheckedCreateInput>
  /**
   * In case the Service was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.ServiceUpdateInput, Prisma.ServiceUncheckedUpdateInput>
}

/**
 * Service delete
 */
export type ServiceDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Service
   */
  select?: Prisma.ServiceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Service
   */
  omit?: Prisma.ServiceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ServiceInclude<ExtArgs> | null
  /**
   * Filter which Service to delete.
   */
  where: Prisma.ServiceWhereUniqueInput
}

/**
 * Service deleteMany
 */
export type ServiceDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Services to delete
   */
  where?: Prisma.ServiceWhereInput
  /**
   * Limit how many Services to delete.
   */
  limit?: number
}

/**
 * Service.dateSlots
 */
export type Service$dateSlotsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DateSlot
   */
  select?: Prisma.DateSlotSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DateSlot
   */
  omit?: Prisma.DateSlotOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DateSlotInclude<ExtArgs> | null
  where?: Prisma.DateSlotWhereInput
  orderBy?: Prisma.DateSlotOrderByWithRelationInput | Prisma.DateSlotOrderByWithRelationInput[]
  cursor?: Prisma.DateSlotWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.DateSlotScalarFieldEnum | Prisma.DateSlotScalarFieldEnum[]
}

/**
 * Service.featureMaps
 */
export type Service$featureMapsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ServiceFeatureMap
   */
  select?: Prisma.ServiceFeatureMapSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ServiceFeatureMap
   */
  omit?: Prisma.ServiceFeatureMapOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ServiceFeatureMapInclude<ExtArgs> | null
  where?: Prisma.ServiceFeatureMapWhereInput
  orderBy?: Prisma.ServiceFeatureMapOrderByWithRelationInput | Prisma.ServiceFeatureMapOrderByWithRelationInput[]
  cursor?: Prisma.ServiceFeatureMapWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.ServiceFeatureMapScalarFieldEnum | Prisma.ServiceFeatureMapScalarFieldEnum[]
}

/**
 * Service without action
 */
export type ServiceDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Service
   */
  select?: Prisma.ServiceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Service
   */
  omit?: Prisma.ServiceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ServiceInclude<ExtArgs> | null
}
